// frontend-svelte/src/lib/components/charts/business/CategoryPieChart.svelte
<script lang="ts">
  import { onMount, createEventDispatcher } from 'svelte';
  import { Pie, Doughnut } from 'svelte-chartjs';
  import {
    Chart as ChartJS,
    Title,
    Tooltip,
    Legend,
    ArcElement,
    type ChartOptions,
    type ChartData,
    type TooltipItem,
  } from 'chart.js';
  import ChartContainer from '../core/ChartContainer.svelte';
  import { formatters, chartTheme, generateColorPalette } from '$lib/utils/charts/formatters';
  import { transformToCategoryPie, type ChartDataPoint } from '$lib/utils/charts/dataTransform';
  import { Search, Eye, EyeOff } from 'lucide-svelte';
  
  // Register Chart.js components
  ChartJS.register(Title, Tooltip, Legend, ArcElement);
  
  const dispatch = createEventDispatcher<{
    sliceClick: { data: ChartDataPoint };
    export: { format: 'png' | 'svg' };
  }>();

  // Props
  export let data: Array<{
    category: string;
    amount: number;
    color?: string;
    [key: string]: any;
  }> = [];
  export let title = 'Распределение по категориям';
  export let subtitle = '';
  export let height = 300;
  export let className = '';
  export let showDonut = true;
  export let showPercentageLabels = true;
  export let showLegend = true;
  export let minSlicePercentage = 2;
  export let loading = false;
  export let error: string | null = null;

  // State
  let hiddenCategories = new Set<string>();
  let activeIndex: number | null = null;
  let searchTerm = '';

  // Process data
  $: transformedData = transformToCategoryPie(data);
  
  $: filteredBySearch = searchTerm 
    ? transformedData.filter(item => 
        item.name.toLowerCase().includes(searchTerm.toLowerCase())
      )
    : transformedData;

  $: processedDataAndOthers = (() => {
    // Separate small slices into "Other" category
    const mainData: ChartDataPoint[] = [];
    let otherSum = 0;
    const otherItems: ChartDataPoint[] = [];
    
    filteredBySearch.forEach((item) => {
      if (item.percentage >= minSlicePercentage && !hiddenCategories.has(item.name)) {
        mainData.push(item);
      } else {
        otherSum += item.value;
        otherItems.push(item);
      }
    });
    
    // Add "Other" category if there are small slices
    if (otherSum > 0) {
      const total = filteredBySearch.reduce((sum, item) => sum + item.value, 0);
      mainData.push({
        name: 'Прочее',
        value: otherSum,
        percentage: (otherSum / total) * 100,
        color: '#9CA3AF',
        isOther: true,
      });
    }

    // Generate colors for main data
    const colors = generateColorPalette(mainData.length);
    const coloredData = mainData.map((item, index) => ({
      ...item,
      color: item.color || colors[index],
    }));

    return {
      chartData: coloredData,
      otherData: otherItems,
    };
  })();

  $: processedData = processedDataAndOthers.chartData;
  $: otherData = processedDataAndOthers.otherData;

  // Chart data
  $: chartData = {
    labels: processedData.map(d => d.name),
    datasets: [{
      data: processedData.map(d => d.value),
      backgroundColor: processedData.map(d => d.color),
      borderColor: '#FFFFFF',
      borderWidth: 2,
      hoverBorderWidth: 3,
      hoverOffset: 4,
    }],
  } as ChartData<'pie'>;

  // Chart options
  $: chartOptions = {
    responsive: true,
    maintainAspectRatio: false,
    cutout: showDonut ? '40%' : '0%',
    plugins: {
      title: {
        display: false,
      },
      legend: {
        display: showLegend,
        position: 'bottom' as const,
        labels: {
          font: {
            size: 12,
          },
          color: chartTheme.colors.gray,
          usePointStyle: true,
          padding: 20,
          generateLabels: (chart) => {
            const data = chart.data;
            if (data.labels?.length && data.datasets.length) {
              return data.labels.map((label, i) => ({
                text: String(label),
                fillStyle: data.datasets[0].backgroundColor?.[i] as string,
                strokeStyle: data.datasets[0].borderColor as string,
                lineWidth: 1,
                hidden: hiddenCategories.has(String(label)),
                index: i,
              }));
            }
            return [];
          },
        },
        onClick: (event, legendItem, legend) => {
          const label = String(legendItem.text);
          if (hiddenCategories.has(label)) {
            hiddenCategories.delete(label);
          } else {
            hiddenCategories.add(label);
          }
          hiddenCategories = new Set(hiddenCategories); // Trigger reactivity
        },
      },
      tooltip: {
        backgroundColor: chartTheme.tooltip.backgroundColor,
        titleColor: chartTheme.tooltip.color,
        bodyColor: chartTheme.tooltip.color,
        borderColor: '#475569',
        borderWidth: 1,
        cornerRadius: 8,
        callbacks: {
          title: (tooltipItems) => {
            return tooltipItems[0]?.label || '';
          },
          label: (context: TooltipItem<'pie'>) => {
            const dataPoint = processedData[context.dataIndex];
            const lines: string[] = [];
            
            lines.push(`Сумма: ${formatters.currency(dataPoint.value)}`);
            lines.push(`Доля: ${dataPoint.percentage.toFixed(1)}%`);
            
            return lines;
          },
        },
      },
    },
    elements: {
      arc: {
        borderWidth: 2,
        hoverBorderWidth: 3,
      },
    },
    onClick: (event, elements) => {
      if (elements.length > 0) {
        const index = elements[0].index;
        const dataPoint = processedData[index];
        
        if (dataPoint && !dataPoint.isOther) {
          dispatch('sliceClick', { data: dataPoint });
        }
        
        activeIndex = activeIndex === index ? null : index;
      }
    },
    animation: {
      animateRotate: true,
      duration: 750,
      easing: 'easeOutQuart',
    },
    // Custom label display
    ...(showPercentageLabels && {
      plugins: {
        ...chartOptions?.plugins,
        datalabels: {
          display: (context: any) => {
            return context.parsed >= minSlicePercentage;
          },
          color: '#FFFFFF',
          font: {
            size: 12,
            weight: 'bold',
          },
          formatter: (value: number, context: any) => {
            const percentage = processedData[context.dataIndex]?.percentage || 0;
            return percentage >= 5 ? `${percentage.toFixed(0)}%` : '';
          },
        },
      },
    }),
  } as ChartOptions<'pie'>;

  // Handle legend click
  function handleLegendClick(dataKey: string) {
    if (hiddenCategories.has(dataKey)) {
      hiddenCategories.delete(dataKey);
    } else {
      hiddenCategories.add(dataKey);
    }
    hiddenCategories = new Set(hiddenCategories);
  }

  // Calculate total for visible slices
  $: visibleTotal = processedData
    .filter(item => !hiddenCategories.has(item.name))
    .reduce((sum, item) => sum + item.value, 0);

  // Summary statistics
  $: summaryStats = (() => {
    const visibleData = processedData.filter(item => !hiddenCategories.has(item.name));
    const categoryCount = visibleData.filter(item => !item.isOther).length;
    const largestPercentage = visibleData.length > 0 ? visibleData[0].percentage : 0;
    const averagePercentage = visibleData.length > 0 ? 100 / visibleData.length : 0;
    
    return { categoryCount, largestPercentage, averagePercentage };
  })();

  let chartRef: HTMLCanvasElement | undefined;

  function handleExport(event: CustomEvent<{ format: 'png' | 'svg' }>) {
    dispatch('export', event.detail);
  }

  const ChartComponent = showDonut ? Doughnut : Pie;
</script>

<ChartContainer
  {title}
  {subtitle}
  {height}
  {className}
  {loading}
  {error}
  exportable={true}
  borderColor="border-l-purple-500"
  on:export={handleExport}
  let:setChartRef
>
  <div slot="controls" class="flex items-center gap-2">
    <div class="relative">
      <Search class="absolute left-2 top-1/2 transform -translate-y-1/2 h-3 w-3 text-gray-400" />
      <input
        type="text"
        placeholder="Поиск категорий..."
        bind:value={searchTerm}
        class="text-xs border border-gray-300 rounded pl-7 pr-2 py-1 w-32"
      />
    </div>
  </div>

  <div class="h-full flex flex-col">
    {#if processedData.length > 0}
      <!-- Chart -->
      <div class="flex-1 relative">
        <svelte:component 
          this={ChartComponent}
          data={chartData}
          options={chartOptions}
          bind:chart={chartRef}
          on:chartInit={() => chartRef && setChartRef(chartRef)}
        />
        
        <!-- Center label for donut chart -->
        {#if showDonut}
          <div class="absolute inset-0 flex items-center justify-center pointer-events-none">
            <div class="text-center">
              <div class="text-lg font-bold text-gray-900">
                {formatters.currency(visibleTotal)}
              </div>
              <div class="text-xs text-gray-500">Всего</div>
            </div>
          </div>
        {/if}
      </div>

      <!-- Custom Legend (if built-in legend is disabled) -->
      {#if !showLegend && processedData.length > 0}
        <div class="flex flex-wrap justify-center gap-3 mt-4">
          {#each processedData as item, index}
            <button
              on:click={() => handleLegendClick(item.name)}
              class="flex items-center gap-2 px-2 py-1 rounded transition-all {
                hiddenCategories.has(item.name) ? 'opacity-50 line-through' : 'hover:bg-gray-100'
              }"
            >
              <div
                class="w-3 h-3 rounded"
                style="background-color: {hiddenCategories.has(item.name) ? '#D1D5DB' : item.color}"
              />
              <span class="text-sm text-gray-600">{item.name}</span>
              {#if hiddenCategories.has(item.name)}
                <EyeOff class="h-3 w-3 text-gray-400" />
              {:else}
                <Eye class="h-3 w-3 text-gray-400" />
              {/if}
            </button>
          {/each}
        </div>
      {/if}
    {:else}
      <div class="flex flex-col justify-center items-center py-12 text-center h-full">
        <div class="h-16 w-16 bg-gray-100 rounded-full flex items-center justify-center mb-4">
          <svg class="h-8 w-8 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 3.055A9.001 9.001 0 1020.945 13H11V3.055z" />
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20.488 9H15V3.512A9.025 9.025 0 0120.488 9z" />
          </svg>
        </div>
        <h3 class="text-lg font-medium text-gray-900 mb-2">Нет данных</h3>
        <p class="text-gray-600">Добавьте категории для отображения распределения</p>
      </div>
    {/if}
  </div>

  <div slot="footer">
    {#if processedData.length > 0}
      <!-- Other categories details -->
      {#if otherData.length > 0}
        <details class="mt-4">
          <summary class="text-sm text-gray-600 cursor-pointer hover:text-gray-800">
            Показать детали категории "Прочее" ({otherData.length} категорий)
          </summary>
          <div class="mt-2 grid grid-cols-1 sm:grid-cols-2 gap-2">
            {#each otherData as item}
              <div class="flex items-center justify-between p-2 bg-gray-50 rounded text-sm">
                <span class="text-gray-600 truncate">{item.name}</span>
                <span class="font-medium text-gray-900 ml-2">
                  {formatters.currency(item.value)}
                </span>
              </div>
            {/each}
          </div>
        </details>
      {/if}

      <!-- Summary stats -->
      <div class="mt-4 grid grid-cols-3 gap-4 text-center text-sm">
        <div class="bg-gray-50 rounded-lg p-2">
          <div class="text-gray-500 text-xs">Категорий</div>
          <div class="font-medium text-gray-900">
            {summaryStats.categoryCount}
          </div>
        </div>
        <div class="bg-gray-50 rounded-lg p-2">
          <div class="text-gray-500 text-xs">Крупнейшая</div>
          <div class="font-medium text-gray-900">
            {summaryStats.largestPercentage.toFixed(1)}%
          </div>
        </div>
        <div class="bg-gray-50 rounded-lg p-2">
          <div class="text-gray-500 text-xs">Средняя</div>
          <div class="font-medium text-gray-900">
            {summaryStats.averagePercentage.toFixed(1)}%
          </div>
        </div>
      </div>
    {/if}
  </div>
</ChartContainer>

// frontend/src/components/charts/business/CategoryPieChart.tsx
import React, { useState, useMemo, useCallback } from 'react';
import {
  PieChart,
  Pie,
  Cell,
  ResponsiveContainer,
  Tooltip,
  Legend,
} from 'recharts';
import { ChartContainer } from '../core/ChartContainer';
import { ChartTheme } from '../utils/ChartTheme';
import { transformToCategoryPie, generateColorPalette, type ChartDataPoint } from '../utils/dataTransform';
import { useChartFilters } from '../hooks/useChartFilters';

interface CategoryPieChartProps {
  data: Array<{
    category: string;
    amount: number;
    color?: string;
    [key: string]: any;
  }>;
  title?: string;
  subtitle?: string;
  height?: number;
  className?: string;
  onSliceClick?: (data: ChartDataPoint) => void;
  showDonut?: boolean;
  showPercentageLabels?: boolean;
  showLegend?: boolean;
  minSlicePercentage?: number; // Minimum percentage to show slice separately
  loading?: boolean;
  error?: string | null;
}

const CustomTooltip: React.FC<any> = ({ active, payload }) => {
  if (active && payload && payload.length) {
    const data = payload[0].payload;
    return (
      <div className="bg-gray-900 text-white p-3 rounded-lg shadow-lg border-none">
        <p className="font-medium mb-2">{data.name}</p>
        <div className="space-y-1 text-sm">
          <div className="flex items-center justify-between gap-4">
            <span>Сумма:</span>
            <span className="font-medium">{ChartTheme.formatters.currency(data.value)}</span>
          </div>
          <div className="flex items-center justify-between gap-4">
            <span>Доля:</span>
            <span className="font-medium">{data.percentage.toFixed(1)}%</span>
          </div>
        </div>
      </div>
    );
  }
  return null;
};

const CustomLegend: React.FC<{
  payload: any[];
  onLegendClick: (dataKey: string) => void;
  hiddenCategories: Set<string>;
}> = ({ payload, onLegendClick, hiddenCategories }) => {
  return (
    <div className="flex flex-wrap justify-center gap-3 mt-4">
      {payload.map((entry, index) => {
        const isHidden = hiddenCategories.has(entry.value);
        return (
          <button
            key={index}
            onClick={() => onLegendClick(entry.value)}
            className={`flex items-center gap-2 px-2 py-1 rounded transition-all ${
              isHidden ? 'opacity-50 line-through' : 'hover:bg-gray-100'
            }`}
          >
            <div
              className="w-3 h-3 rounded"
              style={{ backgroundColor: isHidden ? '#D1D5DB' : entry.color }}
            />
            <span className="text-sm text-gray-600">{entry.value}</span>
          </button>
        );
      })}
    </div>
  );
};

const CustomLabel: React.FC<any> = ({ cx, cy, midAngle, innerRadius, outerRadius, percent }) => {
  if (percent < 0.05) return null; // Don't show labels for slices < 5%
  
  const RADIAN = Math.PI / 180;
  const radius = innerRadius + (outerRadius - innerRadius) * 0.5;
  const x = cx + radius * Math.cos(-midAngle * RADIAN);
  const y = cy + radius * Math.sin(-midAngle * RADIAN);

  return (
    <text
      x={x}
      y={y}
      fill="white"
      textAnchor={x > cx ? 'start' : 'end'}
      dominantBaseline="central"
      fontSize="12"
      fontWeight="bold"
      className="drop-shadow-md"
    >
      {`${(percent * 100).toFixed(0)}%`}
    </text>
  );
};

export const CategoryPieChart: React.FC<CategoryPieChartProps> = ({
  data,
  title = 'Распределение по категориям',
  subtitle,
  height = ChartTheme.sizes.medium.height,
  className = '',
  onSliceClick,
  showDonut = true,
  showPercentageLabels = true,
  showLegend = true,
  minSlicePercentage = 2,
  loading = false,
  error = null,
}) => {
  const [hiddenCategories, setHiddenCategories] = useState<Set<string>>(new Set());
  const [activeIndex, setActiveIndex] = useState<number | null>(null);

  // Transform and process data
  const { chartData, otherData } = useMemo(() => {
    const transformed = transformToCategoryPie(data);
    
    // Separate small slices into "Other" category
    const mainData: ChartDataPoint[] = [];
    let otherSum = 0;
    
    transformed.forEach((item) => {
      if (item.percentage >= minSlicePercentage) {
        mainData.push(item);
      } else {
        otherSum += item.value;
      }
    });
    
    // Add "Other" category if there are small slices
    if (otherSum > 0) {
      const total = transformed.reduce((sum, item) => sum + item.value, 0);
      mainData.push({
        name: 'Прочее',
        value: otherSum,
        percentage: (otherSum / total) * 100,
        color: '#9CA3AF',
        isOther: true,
      });
    }

    // Generate colors for main data
    const colors = generateColorPalette(mainData.length);
    const coloredData = mainData.map((item, index) => ({
      ...item,
      color: item.color || colors[index],
    }));

    return {
      chartData: coloredData,
      otherData: transformed.filter(item => item.percentage < minSlicePercentage),
    };
  }, [data, minSlicePercentage]);

  // Apply filters
  const { filteredData, setSearch, filters } = useChartFilters(
    chartData.filter(item => !hiddenCategories.has(item.name))
  );

  // Handle slice click
  const handleSliceClick = useCallback((data: any, index: number) => {
    setActiveIndex(activeIndex === index ? null : index);
    if (onSliceClick && !data.isOther) {
      onSliceClick(data);
    }
  }, [onSliceClick, activeIndex]);

  // Handle legend click (toggle visibility)
  const handleLegendClick = useCallback((dataKey: string) => {
    setHiddenCategories(prev => {
      const newSet = new Set(prev);
      if (newSet.has(dataKey)) {
        newSet.delete(dataKey);
      } else {
        newSet.add(dataKey);
      }
      return newSet;
    });
  }, []);

  // Calculate total for visible slices
  const visibleTotal = useMemo(() => {
    return filteredData.reduce((sum, item) => sum + item.value, 0);
  }, [filteredData]);

  return (
    <ChartContainer
      title={title}
      subtitle={subtitle}
      height={height}
      className={className}
      loading={loading}
      error={error}
      controls={
        <div className="flex items-center gap-2">
          <input
            type="text"
            placeholder="Поиск категорий..."
            value={filters.search || ''}
            onChange={(e) => setSearch(e.target.value)}
            className="text-xs border border-gray-300 rounded px-2 py-1 w-32"
          />
        </div>
      }
    >
      <div className="h-full flex flex-col">
        {/* Chart */}
        <div className="flex-1">
          <ResponsiveContainer width="100%" height="100%">
            <PieChart>
              <Pie
                data={filteredData}
                cx="50%"
                cy="50%"
                labelLine={false}
                label={showPercentageLabels ? CustomLabel : false}
                outerRadius="80%"
                innerRadius={showDonut ? "40%" : "0%"}
                paddingAngle={2}
                dataKey="value"
                onClick={handleSliceClick}
                onMouseEnter={(_, index) => setActiveIndex(index)}
                onMouseLeave={() => setActiveIndex(null)}
                isAnimationActive={true}
                animationDuration={800}
                animationEasing="ease-out"
              >
                {filteredData.map((entry, index) => (
                  <Cell
                    key={`cell-${index}`}
                    fill={entry.color}
                    stroke={activeIndex === index ? '#374151' : 'none'}
                    strokeWidth={activeIndex === index ? 2 : 0}
                    style={{
                      filter: activeIndex === index ? 'brightness(1.1)' : 'none',
                      cursor: 'pointer',
                    }}
                  />
                ))}
              </Pie>
              <Tooltip content={<CustomTooltip />} />
            </PieChart>
          </ResponsiveContainer>
        </div>

        {/* Center label for donut chart */}
        {showDonut && (
          <div className="absolute inset-0 flex items-center justify-center pointer-events-none">
            <div className="text-center">
              <div className="text-lg font-bold text-gray-900">
                {ChartTheme.formatters.currency(visibleTotal)}
              </div>
              <div className="text-xs text-gray-500">Всего</div>
            </div>
          </div>
        )}

        {/* Legend */}
        {showLegend && (
          <CustomLegend
            payload={filteredData.map(item => ({
              value: item.name,
              color: item.color,
            }))}
            onLegendClick={handleLegendClick}
            hiddenCategories={hiddenCategories}
          />
        )}

        {/* Other categories details */}
        {otherData.length > 0 && (
          <details className="mt-4">
            <summary className="text-sm text-gray-600 cursor-pointer hover:text-gray-800">
              Показать детали категории "Прочее" ({otherData.length} категорий)
            </summary>
            <div className="mt-2 grid grid-cols-1 sm:grid-cols-2 gap-2">
              {otherData.map((item, index) => (
                <div key={index} className="flex items-center justify-between p-2 bg-gray-50 rounded text-sm">
                  <span className="text-gray-600 truncate">{item.name}</span>
                  <span className="font-medium text-gray-900 ml-2">
                    {ChartTheme.formatters.currency(item.value)}
                  </span>
                </div>
              ))}
            </div>
          </details>
        )}

        {/* Summary stats */}
        <div className="mt-4 grid grid-cols-3 gap-4 text-center text-sm">
          <div className="bg-gray-50 rounded-lg p-2">
            <div className="text-gray-500 text-xs">Категорий</div>
            <div className="font-medium text-gray-900">
              {filteredData.filter(item => !item.isOther).length}
            </div>
          </div>
          <div className="bg-gray-50 rounded-lg p-2">
            <div className="text-gray-500 text-xs">Крупнейшая</div>
            <div className="font-medium text-gray-900">
              {filteredData.length > 0 ? `${filteredData[0].percentage.toFixed(1)}%` : '0%'}
            </div>
          </div>
          <div className="bg-gray-50 rounded-lg p-2">
            <div className="text-gray-500 text-xs">Средняя</div>
            <div className="font-medium text-gray-900">
              {filteredData.length > 0 ? `${(100 / filteredData.length).toFixed(1)}%` : '0%'}
            </div>
          </div>
        </div>
      </div>
    </ChartContainer>
  );
};

// Compact version for dashboards
export const CategoryPieChartCompact: React.FC<Omit<CategoryPieChartProps, 'height' | 'showLegend'>> = (props) => {
  return (
    <CategoryPieChart
      {...props}
      height={200}
      showLegend={false}
      showPercentageLabels={true}
    />
  );
};

export default CategoryPieChart;
