// frontend/src/components/ui/alert-dialog.tsx
import * as React from "react"
import * as AlertDialogPrimitive from "@radix-ui/react-alert-dialog"

import { cn } from "../../lib/utils"
import { buttonVariants } from "./button"

const AlertDialog = AlertDialogPrimitive.Root

const AlertDialogTrigger = AlertDialogPrimitive.Trigger

const AlertDialogPortal = AlertDialogPrimitive.Portal

const AlertDialogOverlay = React.forwardRef<
  React.ElementRef<typeof AlertDialogPrimitive.Overlay>,
  React.ComponentPropsWithoutRef<typeof AlertDialogPrimitive.Overlay>
>(({ className, ...props }, ref) => (
  <AlertDialogPrimitive.Overlay
    className={cn(
      "fixed inset-0 z-50 bg-black/80 data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0",
      className
    )}
    {...props}
    ref={ref}
  />
))
AlertDialogOverlay.displayName = AlertDialogPrimitive.Overlay.displayName

const AlertDialogContent = React.forwardRef<
  React.ElementRef<typeof AlertDialogPrimitive.Content>,
  React.ComponentPropsWithoutRef<typeof AlertDialogPrimitive.Content>
>(({ className, ...props }, ref) => (
  <AlertDialogPortal>
    <AlertDialogOverlay />
    <AlertDialogPrimitive.Content
      ref={ref}
      className={cn(
        "fixed left-[50%] top-[50%] z-50 grid w-full max-w-lg translate-x-[-50%] translate-y-[-50%] gap-4 border bg-background p-6 shadow-lg duration-200 data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95 data-[state=closed]:slide-out-to-left-1/2 data-[state=closed]:slide-out-to-top-[48%] data-[state=open]:slide-in-from-left-1/2 data-[state=open]:slide-in-from-top-[48%] sm:rounded-lg",
        className
      )}
      {...props}
    />
  </AlertDialogPortal>
))
AlertDialogContent.displayName = AlertDialogPrimitive.Content.displayName

const AlertDialogHeader = ({
  className,
  ...props
}: React.HTMLAttributes<HTMLDivElement>) => (
  <div
    className={cn(
      "flex flex-col space-y-2 text-center sm:text-left",
      className
    )}
    {...props}
  />
)
AlertDialogHeader.displayName = "AlertDialogHeader"

const AlertDialogFooter = ({
  className,
  ...props
}: React.HTMLAttributes<HTMLDivElement>) => (
  <div
    className={cn(
      "flex flex-col-reverse sm:flex-row sm:justify-end sm:space-x-2",
      className
    )}
    {...props}
  />
)
AlertDialogFooter.displayName = "AlertDialogFooter"

const AlertDialogTitle = React.forwardRef<
  React.ElementRef<typeof AlertDialogPrimitive.Title>,
  React.ComponentPropsWithoutRef<typeof AlertDialogPrimitive.Title>
>(({ className, ...props }, ref) => (
  <AlertDialogPrimitive.Title
    ref={ref}
    className={cn("text-lg font-semibold", className)}
    {...props}
  />
))
AlertDialogTitle.displayName = AlertDialogPrimitive.Title.displayName

const AlertDialogDescription = React.forwardRef<
  React.ElementRef<typeof AlertDialogPrimitive.Description>,
  React.ComponentPropsWithoutRef<typeof AlertDialogPrimitive.Description>
>(({ className, ...props }, ref) => (
  <AlertDialogPrimitive.Description
    ref={ref}
    className={cn("text-sm text-muted-foreground", className)}
    {...props}
  />
))
AlertDialogDescription.displayName =
  AlertDialogPrimitive.Description.displayName

const AlertDialogAction = React.forwardRef<
  React.ElementRef<typeof AlertDialogPrimitive.Action>,
  React.ComponentPropsWithoutRef<typeof AlertDialogPrimitive.Action>
>(({ className, ...props }, ref) => (
  <AlertDialogPrimitive.Action
    ref={ref}
    className={cn(buttonVariants(), className)}
    {...props}
  />
))
AlertDialogAction.displayName = AlertDialogPrimitive.Action.displayName

const AlertDialogCancel = React.forwardRef<
  React.ElementRef<typeof AlertDialogPrimitive.Cancel>,
  React.ComponentPropsWithoutRef<typeof AlertDialogPrimitive.Cancel>
>(({ className, ...props }, ref) => (
  <AlertDialogPrimitive.Cancel
    ref={ref}
    className={cn(
      buttonVariants({ variant: "outline" }),
      "mt-2 sm:mt-0",
      className
    )}
    {...props}
  />
))
AlertDialogCancel.displayName = AlertDialogPrimitive.Cancel.displayName

export {
  AlertDialog,
  AlertDialogPortal,
  AlertDialogOverlay,
  AlertDialogTrigger,
  AlertDialogContent,
  AlertDialogHeader,
  AlertDialogFooter,
  AlertDialogTitle,
  AlertDialogDescription,
  AlertDialogAction,
  AlertDialogCancel,
}

// frontend-svelte/src/lib/components/ui/AlertDialog.svelte
<!--
  AlertDialog component - модальное диалоговое окно для подтверждения действий
  Адаптировано из React версии для использования в Svelte
-->
<script lang="ts">
  import { createEventDispatcher, onMount } from 'svelte';
  import { fade, scale } from 'svelte/transition';
  import Button from './Button.svelte';
  import { cn } from '$lib/utils/cn';

  // Props
  export let open = false;
  export let title = '';
  export let description = '';
  export let destructive = false;
  export let cancelText = 'Отмена';
  export let actionText = 'Подтвердить';
  export let disabled = false;
  
  // CSS classes
  export let className = '';
  export let overlayClass = '';
  export let contentClass = '';
  export let headerClass = '';
  export let footerClass = '';
  export let titleClass = '';
  export let descriptionClass = '';

  const dispatch = createEventDispatcher<{
    cancel: void;
    confirm: void;
    close: void;
  }>();

  let dialogElement: HTMLDialogElement;

  // Управление открытием/закрытием
  $: if (dialogElement) {
    if (open) {
      dialogElement.showModal();
      document.body.style.overflow = 'hidden';
    } else {
      dialogElement.close();
      document.body.style.overflow = '';
    }
  }

  // Обработчики событий
  function handleCancel() {
    open = false;
    dispatch('cancel');
    dispatch('close');
  }

  function handleConfirm() {
    open = false;
    dispatch('confirm');
    dispatch('close');
  }

  function handleBackdropClick(event: MouseEvent) {
    if (event.target === dialogElement) {
      handleCancel();
    }
  }

  function handleKeydown(event: KeyboardEvent) {
    if (event.key === 'Escape') {
      handleCancel();
    }
  }

  onMount(() => {
    return () => {
      document.body.style.overflow = '';
    };
  });
</script>

<!-- svelte-ignore a11y-click-events-have-key-events a11y-no-noninteractive-element-interactions -->
<dialog
  bind:this={dialogElement}
  class={cn('modal', className)}
  on:click={handleBackdropClick}
  on:keydown={handleKeydown}
>
  {#if open}
    <!-- Overlay -->
    <div
      class={cn(
        'fixed inset-0 z-50 bg-black/80',
        overlayClass
      )}
      transition:fade={{ duration: 200 }}
    />
    
    <!-- Dialog Content -->
    <div
      class={cn(
        'fixed left-[50%] top-[50%] z-50 grid w-full max-w-lg translate-x-[-50%] translate-y-[-50%] gap-4 border bg-background p-6 shadow-lg duration-200 sm:rounded-lg',
        contentClass
      )}
      transition:scale={{ duration: 200, start: 0.95 }}
      role="alertdialog"
      aria-labelledby="alert-dialog-title"
      aria-describedby="alert-dialog-description"
    >
      <!-- Header -->
      <div
        class={cn(
          'flex flex-col space-y-2 text-center sm:text-left',
          headerClass
        )}
      >
        {#if title}
          <h2
            id="alert-dialog-title"
            class={cn(
              'text-lg font-semibold',
              titleClass
            )}
          >
            {title}
          </h2>
        {/if}
        
        {#if description}
          <p
            id="alert-dialog-description"
            class={cn(
              'text-sm text-muted-foreground',
              descriptionClass
            )}
          >
            {description}
          </p>
        {/if}
      </div>

      <!-- Slot для кастомного контента -->
      <slot />

      <!-- Footer -->
      <div
        class={cn(
          'flex flex-col-reverse sm:flex-row sm:justify-end sm:space-x-2',
          footerClass
        )}
      >
        <Button
          variant="outline"
          class="mt-2 sm:mt-0"
          on:click={handleCancel}
          {disabled}
        >
          {cancelText}
        </Button>
        
        <Button
          variant={destructive ? 'destructive' : 'default'}
          on:click={handleConfirm}
          {disabled}
        >
          {actionText}
        </Button>
      </div>
    </div>
  {/if}
</dialog>

<style>
  .modal {
    margin: 0;
    padding: 0;
    border: none;
    background: transparent;
    max-width: none;
    max-height: none;
  }

  .modal::backdrop {
    display: none;
  }
</style>
