// frontend/src/components/auth/PasswordLogin.tsx
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuthStore } from '../../stores/authStore';
import { authService } from '../../services/authService';

export const PasswordLogin: React.FC = () => {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  
  const navigate = useNavigate();
  const setUser = useAuthStore((state) => state.setUser);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setIsLoading(true);

    try {
      const response = await authService.loginWithPassword(username, password);
      
      if (response.success && response.user) {
        setUser({
          user_id: response.user.id,
          user_name: response.user.username || '',
          user_telegram_id: 0,
          first_name: response.user.firstName || '',
          last_name: response.user.lastName || '',
          username: response.user.username || '',
          authMethod: 'password'
        });
        navigate('/');
      } else {
        setError('Login failed');
      }
    } catch (err: any) {
      setError(err.response?.data?.error || 'Login failed. Please try again.');
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-md w-full space-y-8">
        <div>
          <h2 className="mt-6 text-center text-3xl font-extrabold text-gray-900">
            Sign in to your account
          </h2>
          <p className="mt-2 text-center text-sm text-gray-600">
            Or{' '}
            <button
              onClick={() => navigate('/login')}
              className="font-medium text-blue-600 hover:text-blue-500"
            >
              sign in with Telegram
            </button>
          </p>
        </div>
        <form className="mt-8 space-y-6" onSubmit={handleSubmit}>
          <input type="hidden" name="remember" value="true" />
          <div className="rounded-md shadow-sm -space-y-px">
            <div>
              <label htmlFor="username" className="sr-only">
                Username
              </label>
              <input
                id="username"
                name="username"
                type="text"
                autoComplete="username"
                required
                className="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-blue-500 focus:border-blue-500 focus:z-10 sm:text-sm"
                placeholder="Username"
                value={username}
                onChange={(e) => setUsername(e.target.value)}
              />
            </div>
            <div>
              <label htmlFor="password" className="sr-only">
                Password
              </label>
              <input
                id="password"
                name="password"
                type="password"
                autoComplete="current-password"
                required
                className="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-b-md focus:outline-none focus:ring-blue-500 focus:border-blue-500 focus:z-10 sm:text-sm"
                placeholder="Password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
              />
            </div>
          </div>

          {error && (
            <div className="rounded-md bg-red-50 p-4">
              <div className="flex">
                <div className="ml-3">
                  <h3 className="text-sm font-medium text-red-800">{error}</h3>
                </div>
              </div>
            </div>
          )}

          <div>
            <button
              type="submit"
              disabled={isLoading}
              className="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {isLoading ? 'Signing in...' : 'Sign in'}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

// frontend-svelte/src/lib/components/auth/PasswordLogin.svelte
<script lang="ts">
  import { goto } from '$app/navigation';
  import { setCurrentUser } from '$lib/stores/auth.store';
  import { useToast } from '$lib/stores/toast.store';
  import { api } from '$lib/services/api';
  import Card from '$lib/components/ui/Card.svelte';
  import Button from '$lib/components/ui/Button.svelte';
  import Input from '$lib/components/ui/Input.svelte';
  import type { User } from '$types';

  export let onSwitchToTelegram: () => void = () => {};

  let username = '';
  let password = '';
  let error = '';
  let isLoading = false;
  
  const toast = useToast();

  interface PasswordAuthResponse {
    success: boolean;
    user?: {
      id: number;
      username: string;
      firstName?: string;
      lastName?: string;
    };
    token?: string;
    error?: string;
  }

  async function handleSubmit() {
    error = '';
    isLoading = true;

    try {
      const response = await api.post<PasswordAuthResponse>('/auth/password', {
        username,
        password
      });

      if (response.success && response.user) {
        const user: User = {
          user_id: response.user.id,
          user_name: response.user.username || '',
          user_telegram_id: 0,
          first_name: response.user.firstName || '',
          last_name: response.user.lastName || '',
          username: response.user.username || '',
          authMethod: 'password'
        };

        setCurrentUser(user);
        
        if (response.token) {
          localStorage.setItem('auth_token', response.token);
        }

        toast.success('Успешно', 'Вы вошли в систему');
        goto('/dashboard');
      } else {
        error = response.error || 'Ошибка входа';
      }
    } catch (err: any) {
      console.error('Password login error:', err);
      error = err.message || 'Ошибка входа. Попробуйте еще раз.';
    } finally {
      isLoading = false;
    }
  }

  function handleKeydown(event: KeyboardEvent) {
    if (event.key === 'Enter' && username && password && !isLoading) {
      handleSubmit();
    }
  }
</script>

<Card class="max-w-md w-full p-8 space-y-6">
  <div class="text-center">
    <h1 class="text-3xl font-bold text-gray-900 mb-2">
      💰 Family Budget
    </h1>
    <p class="text-gray-600">
      Управление семейным бюджетом
    </p>
  </div>

  <div class="space-y-4">
    <h2 class="text-xl font-semibold text-center text-gray-800">
      Вход с логином и паролем
    </h2>
    
    <p class="text-sm text-gray-600 text-center">
      Введите ваши данные для входа в систему
    </p>

    <form on:submit|preventDefault={handleSubmit} class="space-y-4">
      <div class="space-y-4">
        <div>
          <label for="username" class="block text-sm font-medium text-gray-700 mb-1">
            Имя пользователя
          </label>
          <Input
            id="username"
            type="text"
            bind:value={username}
            placeholder="Введите имя пользователя"
            required
            disabled={isLoading}
            on:keydown={handleKeydown}
            class="w-full"
          />
        </div>

        <div>
          <label for="password" class="block text-sm font-medium text-gray-700 mb-1">
            Пароль
          </label>
          <Input
            id="password"
            type="password"
            bind:value={password}
            placeholder="Введите пароль"
            required
            disabled={isLoading}
            on:keydown={handleKeydown}
            class="w-full"
          />
        </div>
      </div>

      {#if error}
        <div class="rounded-md bg-red-50 p-4">
          <div class="text-sm text-red-800">{error}</div>
        </div>
      {/if}

      <Button
        type="submit"
        disabled={!username || !password || isLoading}
        class="w-full"
      >
        {#if isLoading}
          Вход...
        {:else}
          Войти
        {/if}
      </Button>
    </form>

    <div class="relative">
      <div class="absolute inset-0 flex items-center">
        <div class="w-full border-t border-gray-300"></div>
      </div>
      <div class="relative flex justify-center text-sm">
        <span class="px-2 bg-white text-gray-500">Или</span>
      </div>
    </div>

    <Button
      variant="outline"
      class="w-full"
      on:click={onSwitchToTelegram}
    >
      Войти через Telegram
    </Button>
  </div>

  <div class="text-xs text-gray-500 text-center">
    <p>
      Используйте ваше имя пользователя и пароль для входа в систему Family Budget.
    </p>
  </div>
</Card>
