// frontend-svelte/src/lib/components/products/ProductList.svelte
<script lang="ts">
  import { onMount, createEventDispatcher } from 'svelte';
  import { productService, type Product } from '$lib/services/product.service';
  import { toastStore } from '$lib/stores/toast.store';
  import Card from '$lib/components/ui/Card.svelte';
  import Button from '$lib/components/ui/Button.svelte';
  import Input from '$lib/components/ui/Input.svelte';
  import DataTable from '$lib/components/common/DataTable.svelte';
  import Loading from '$lib/components/common/Loading.svelte';
  import { Search, Filter, Trash2 } from 'lucide-svelte';

  export let onEdit: ((product: Product) => void) | null = null;
  export let refreshKey = 0;

  const dispatch = createEventDispatcher<{
    edit: Product;
  }>();

  let products: Product[] = [];
  let isLoading = true;
  let selectedProducts = new Set<number>();
  let filters = {
    search: '',
    category: '',
    status: ''
  };

  // Фильтрованные продукты
  $: filteredProducts = products.filter(product => {
    if (filters.search && !product.product_name.toLowerCase().includes(filters.search.toLowerCase())) {
      return false;
    }
    if (filters.category && product.category_name !== filters.category) {
      return false;
    }
    if (filters.status) {
      if (filters.status === 'active' && !product.is_active) return false;
      if (filters.status === 'inactive' && product.is_active) return false;
    }
    return true;
  });

  // Получение уникальных категорий
  $: categories = [...new Set(products.map(p => p.category_name).filter(Boolean))];

  // Обновление при изменении refreshKey
  $: if (refreshKey) {
    loadProducts();
  }

  onMount(() => {
    loadProducts();
  });

  async function loadProducts() {
    try {
      isLoading = true;
      const data = await productService.getAll();
      products = data;
    } catch (error: any) {
      console.error('Ошибка загрузки продуктов:', error);
      toastStore.error(error.message || 'Не удалось загрузить список продуктов');
    } finally {
      isLoading = false;
    }
  }

  async function handleBulkDelete() {
    if (!confirm(`Вы уверены, что хотите удалить ${selectedProducts.size} продуктов?`)) {
      return;
    }

    try {
      await Promise.all(Array.from(selectedProducts).map(id => productService.delete(id)));
      toastStore.success(`Удалено ${selectedProducts.size} продуктов`);
      selectedProducts.clear();
      selectedProducts = selectedProducts; // Trigger reactivity
      await loadProducts();
    } catch (error: any) {
      console.error('Ошибка при удалении продуктов:', error);
      toastStore.error(error.message || 'Не удалось удалить продукты');
    }
  }

  async function handleDelete(productId: number) {
    if (!confirm('Вы уверены, что хотите удалить этот продукт?')) {
      return;
    }

    try {
      await productService.delete(productId);
      toastStore.success('Продукт удален');
      await loadProducts();
    } catch (error: any) {
      console.error('Ошибка при удалении продукта:', error);
      toastStore.error(error.message || 'Не удалось удалить продукт');
    }
  }

  function handleEdit(product: Product) {
    if (onEdit) {
      onEdit(product);
    } else {
      dispatch('edit', product);
    }
  }

  function clearFilters() {
    filters = { search: '', category: '', status: '' };
  }

  function toggleSelectAll(checked: boolean) {
    if (checked) {
      selectedProducts = new Set(filteredProducts.map(p => p.product_id!));
    } else {
      selectedProducts.clear();
    }
    selectedProducts = selectedProducts; // Trigger reactivity
  }

  function toggleSelect(productId: number) {
    if (selectedProducts.has(productId)) {
      selectedProducts.delete(productId);
    } else {
      selectedProducts.add(productId);
    }
    selectedProducts = selectedProducts; // Trigger reactivity
  }

  // Колонки для таблицы
  const columns = [
    {
      key: 'select',
      title: '',
      width: '40px'
    },
    {
      key: 'product_name',
      title: 'Наименование',
      sortable: true
    },
    {
      key: 'category_name',
      title: 'Категория',
      sortable: true
    },
    {
      key: 'unit_measure',
      title: 'Единица',
      sortable: true
    },
    {
      key: 'barcode',
      title: 'Штрихкод'
    },
    {
      key: 'is_active',
      title: 'Статус',
      width: '100px'
    },
    {
      key: 'description',
      title: 'Описание'
    },
    {
      key: 'actions',
      title: 'Действия',
      width: '150px'
    }
  ];
</script>

<div class="space-y-6">
  <!-- Фильтры и действия -->
  <Card title="Управление продуктами">
    <div class="space-y-4">
      <!-- Строка поиска и фильтров -->
      <div class="grid grid-cols-1 md:grid-cols-4 gap-4">
        <div class="relative">
          <Search class="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 h-4 w-4" />
          <Input
            placeholder="Поиск продуктов..."
            bind:value={filters.search}
            class="pl-10"
          />
        </div>
        
        <select
          bind:value={filters.category}
          class="block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500 sm:text-sm"
        >
          <option value="">Все категории</option>
          {#each categories as category}
            <option value={category}>{category}</option>
          {/each}
        </select>
        
        <select
          bind:value={filters.status}
          class="block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500 sm:text-sm"
        >
          <option value="">Все статусы</option>
          <option value="active">Активные</option>
          <option value="inactive">Неактивные</option>
        </select>

        <div class="flex gap-2">
          <Button
            variant="secondary"
            size="sm"
            on:click={clearFilters}
          >
            <Filter class="h-4 w-4 mr-1" />
            Сбросить
          </Button>
        </div>
      </div>

      <!-- Действия -->
      {#if selectedProducts.size > 0}
        <div class="flex gap-2">
          <Button
            variant="secondary"
            size="sm"
            on:click={handleBulkDelete}
            class="text-red-600 hover:text-red-700"
          >
            <Trash2 class="h-4 w-4 mr-1" />
            Удалить выбранные ({selectedProducts.size})
          </Button>
        </div>
      {/if}
    </div>
  </Card>

  <!-- Таблица продуктов -->
  <Card title={`Список продуктов (${filteredProducts.length})`}>
    {#if isLoading}
      <Loading />
    {:else}
      <div class="overflow-x-auto">
        <table class="min-w-full divide-y divide-gray-200">
          <thead class="bg-gray-50">
            <tr>
              <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                <input
                  type="checkbox"
                  checked={filteredProducts.length > 0 && selectedProducts.size === filteredProducts.length}
                  on:change={(e) => toggleSelectAll(e.currentTarget.checked)}
                  class="rounded border-gray-300"
                />
              </th>
              <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Наименование
              </th>
              <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Категория
              </th>
              <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Единица
              </th>
              <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Штрихкод
              </th>
              <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Статус
              </th>
              <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Описание
              </th>
              <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Действия
              </th>
            </tr>
          </thead>
          <tbody class="bg-white divide-y divide-gray-200">
            {#each filteredProducts as product (product.product_id)}
              <tr class="hover:bg-gray-50">
                <td class="px-6 py-4 whitespace-nowrap">
                  <input
                    type="checkbox"
                    checked={selectedProducts.has(product.product_id!)}
                    on:change={() => toggleSelect(product.product_id!)}
                    class="rounded border-gray-300"
                  />
                </td>
                <td class="px-6 py-4 whitespace-nowrap font-medium text-gray-900">
                  {product.product_name}
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                  {product.category_name || '—'}
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                  {product.unit_measure || '—'}
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                  {product.barcode || '—'}
                </td>
                <td class="px-6 py-4 whitespace-nowrap">
                  <span class="px-2 py-1 rounded-full text-xs font-medium {
                    product.is_active 
                      ? 'bg-green-100 text-green-800' 
                      : 'bg-red-100 text-red-800'
                  }">
                    {product.is_active ? 'Активный' : 'Неактивный'}
                  </span>
                </td>
                <td class="px-6 py-4 text-sm text-gray-600">
                  {#if product.description}
                    <span title={product.description}>
                      {product.description.length > 30 ? `${product.description.substring(0, 30)}...` : product.description}
                    </span>
                  {:else}
                    <span class="text-gray-400">—</span>
                  {/if}
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium">
                  <div class="flex gap-2">
                    <Button
                      variant="secondary"
                      size="sm"
                      on:click={() => handleEdit(product)}
                    >
                      Изменить
                    </Button>
                    <Button
                      variant="secondary"
                      size="sm"
                      on:click={() => handleDelete(product.product_id!)}
                      class="text-red-600 hover:text-red-700"
                    >
                      Удалить
                    </Button>
                  </div>
                </td>
              </tr>
            {/each}
          </tbody>
        </table>

        {#if filteredProducts.length === 0}
          <div class="text-center py-12">
            <div class="text-gray-500">Нет продуктов, соответствующих фильтрам</div>
          </div>
        {/if}
      </div>
    {/if}
  </Card>
</div>

// frontend/src/components/products/ProductList.tsx
import React, { useState, useEffect } from 'react';
import { DataTable } from '../common/DataTable';
import { Card } from '../common/Card';
import { Button } from '../common/form/Button';
import { Loading } from '../common/Loading';
import { useToast } from '../common/ToastContainer';
import { Input } from '../common/form/Input';
import { Search, Filter, Trash2 } from 'lucide-react';
import type { ColumnDef } from '@tanstack/react-table';
import type { Product } from '../../types';
import { productService } from '../../services';

interface ProductListProps {
  onEdit?: (product: Product) => void;
  refreshKey?: number;
}

export const ProductList: React.FC<ProductListProps> = ({ 
  onEdit,
  refreshKey = 0 
}) => {
  const [products, setProducts] = useState<Product[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [selectedProducts, setSelectedProducts] = useState<Set<number>>(new Set());
  const [filters, setFilters] = useState({
    search: '',
    category: '',
    status: ''
  });
  const toast = useToast();

  useEffect(() => {
    loadProducts();
  }, [refreshKey]);

  const loadProducts = async () => {
    try {
      setIsLoading(true);
      const data = await productService.getAll();
      setProducts(data);
    } catch (error: any) {
      console.error('Ошибка загрузки продуктов:', error);
      toast.error('Ошибка', error.message || 'Не удалось загрузить список продуктов');
    } finally {
      setIsLoading(false);
    }
  };

  // Фильтрация продуктов
  const filteredProducts = products.filter(product => {
    if (filters.search && !product.product_name.toLowerCase().includes(filters.search.toLowerCase())) {
      return false;
    }
    if (filters.category && product.category_name !== filters.category) {
      return false;
    }
    if (filters.status) {
      if (filters.status === 'active' && !product.is_active) return false;
      if (filters.status === 'inactive' && product.is_active) return false;
    }
    return true;
  });

  // Получение уникальных категорий
  const categories = [...new Set(products.map(p => p.category_name).filter(Boolean))];

  const handleBulkDelete = async () => {
    if (!window.confirm(`Вы уверены, что хотите удалить ${selectedProducts.size} продуктов?`)) {
      return;
    }

    try {
      await Promise.all(Array.from(selectedProducts).map(id => productService.delete(id)));
      toast.success('Успешно', `Удалено ${selectedProducts.size} продуктов`);
      setSelectedProducts(new Set());
      loadProducts();
    } catch (error: any) {
      console.error('Ошибка при удалении продуктов:', error);
      toast.error('Ошибка', error.message || 'Не удалось удалить продукты');
    }
  };

  const handleDelete = async (productId: number) => {
    if (!window.confirm('Вы уверены, что хотите удалить этот продукт?')) {
      return;
    }

    try {
      await productService.delete(productId);
      toast.success('Успешно', 'Продукт удален');
      loadProducts();
    } catch (error: any) {
      console.error('Ошибка при удалении продукта:', error);
      toast.error('Ошибка', error.message || 'Не удалось удалить продукт');
    }
  };

  const columns: ColumnDef<Product>[] = [
    {
      id: 'select',
      header: ({ table }) => (
        <input
          type="checkbox"
          checked={table.getIsAllPageRowsSelected()}
          onChange={(e) => {
            const checked = e.target.checked;
            table.toggleAllPageRowsSelected(checked);
            if (checked) {
              const newSelected = new Set(selectedProducts);
              table.getRowModel().rows.forEach(row => {
                newSelected.add(row.original.product_id!);
              });
              setSelectedProducts(newSelected);
            } else {
              setSelectedProducts(new Set());
            }
          }}
          className="rounded border-gray-300"
        />
      ),
      cell: ({ row }) => (
        <input
          type="checkbox"
          checked={selectedProducts.has(row.original.product_id!)}
          onChange={(e) => {
            const newSelected = new Set(selectedProducts);
            if (e.target.checked) {
              newSelected.add(row.original.product_id!);
            } else {
              newSelected.delete(row.original.product_id!);
            }
            setSelectedProducts(newSelected);
          }}
          className="rounded border-gray-300"
        />
      ),
    },
    {
      header: 'Наименование',
      accessorKey: 'product_name',
    },
    {
      header: 'Категория',
      accessorKey: 'category_name',
    },
    {
      header: 'Единица',
      accessorKey: 'unit_measure',
    },
    {
      header: 'Штрихкод',
      accessorKey: 'barcode',
      cell: ({ row }) => {
        const barcode = row.original.barcode;
        return barcode || <span className="text-gray-400">—</span>;
      },
    },
    {
      header: 'Статус',
      accessorKey: 'is_active',
      cell: ({ row }) => {
        const isActive = row.original.is_active;
        return (
          <span className={`px-2 py-1 rounded-full text-xs font-medium ${
            isActive 
              ? 'bg-green-100 text-green-800' 
              : 'bg-red-100 text-red-800'
          }`}>
            {isActive ? 'Активный' : 'Неактивный'}
          </span>
        );
      },
    },
    {
      header: 'Описание',
      accessorKey: 'description',
      cell: ({ row }) => {
        const description = row.original.description;
        return description ? (
          <span className="text-sm text-gray-600" title={description}>
            {description.length > 30 ? `${description.substring(0, 30)}...` : description}
          </span>
        ) : (
          <span className="text-gray-400">—</span>
        );
      },
    },
    {
      header: 'Действия',
      id: 'actions',
      cell: ({ row }) => {
        const product = row.original;
        return (
          <div className="flex gap-2">
            {onEdit && (
              <Button
                variant="secondary"
                size="sm"
                onClick={() => onEdit(product)}
              >
                Изменить
              </Button>
            )}
            <Button
              variant="secondary"
              size="sm"
              onClick={() => handleDelete(product.product_id!)}
              className="text-red-600 hover:text-red-700"
            >
              Удалить
            </Button>
          </div>
        );
      },
    },
  ];

  if (isLoading) {
    return (
      <Card title="Список продуктов">
        <Loading />
      </Card>
    );
  }

  return (
    <div className="space-y-6">
      {/* Фильтры и действия */}
      <Card title="Управление продуктами">
        <div className="space-y-4">
          {/* Строка поиска и фильтров */}
          <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
            <div className="relative">
              <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 h-4 w-4" />
              <Input
                placeholder="Поиск продуктов..."
                value={filters.search}
                onChange={(e) => setFilters(prev => ({ ...prev, search: e.target.value }))}
                className="pl-10"
              />
            </div>
            
            <select
              value={filters.category}
              onChange={(e) => setFilters(prev => ({ ...prev, category: e.target.value }))}
              className="block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500 sm:text-sm"
            >
              <option value="">Все категории</option>
              {categories.map(category => (
                <option key={category} value={category}>{category}</option>
              ))}
            </select>
            
            <select
              value={filters.status}
              onChange={(e) => setFilters(prev => ({ ...prev, status: e.target.value }))}
              className="block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500 sm:text-sm"
            >
              <option value="">Все статусы</option>
              <option value="active">Активные</option>
              <option value="inactive">Неактивные</option>
            </select>

            <div className="flex gap-2">
              <Button
                variant="secondary"
                size="sm"
                onClick={() => setFilters({ search: '', category: '', status: '' })}
              >
                <Filter className="h-4 w-4 mr-1" />
                Сбросить
              </Button>
            </div>
          </div>

          {/* Действия */}
          {selectedProducts.size > 0 && (
            <div className="flex gap-2">
              <Button
                variant="secondary"
                size="sm"
                onClick={handleBulkDelete}
                className="text-red-600 hover:text-red-700"
              >
                <Trash2 className="h-4 w-4 mr-1" />
                Удалить выбранные ({selectedProducts.size})
              </Button>
            </div>
          )}
        </div>
      </Card>

      {/* Таблица продуктов */}
      <Card title={`Список продуктов (${filteredProducts.length})`}>
        {isLoading ? (
          <Loading />
        ) : (
          <DataTable
            data={filteredProducts}
            columns={columns}
            pageSize={15}
          />
        )}
      </Card>

    </div>
  );
};
