// frontend-svelte/src/routes/login/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { goto } from '$app/navigation';
  import { page } from '$app/stores';
  import { isAuthenticated } from '$lib/stores/auth.store';
  import { authService } from '$lib/services/auth.service';
  import TelegramLoginButton from '$lib/components/auth/TelegramLoginButton.svelte';
  import PasswordLogin from '$lib/components/auth/PasswordLogin.svelte';
  import Card from '$lib/components/ui/Card.svelte';
  import Button from '$lib/components/ui/Button.svelte';
  
  let returnUrl: string | null = null;
  let passwordAuthEnabled = false;
  let showPasswordLogin = false;
  let loading = false;
  
  onMount(async () => {
    // Redirect if already authenticated
    if ($isAuthenticated) {
      goto('/dashboard');
      return;
    }
    
    // Get return URL from query parameters
    returnUrl = $page.url.searchParams.get('returnUrl');
    
    // Check if password auth is enabled
    try {
      loading = true;
      const response = await authService.checkPasswordAuthEnabled();
      passwordAuthEnabled = response.enabled;
    } catch (error) {
      console.error('Error checking password auth:', error);
    } finally {
      loading = false;
    }
  });
  
  // Watch for authentication changes
  $: if ($isAuthenticated && returnUrl) {
    goto(returnUrl);
  } else if ($isAuthenticated) {
    goto('/dashboard');
  }
  
  function handleSwitchToTelegram() {
    showPasswordLogin = false;
  }
  
  function handleSwitchToPassword() {
    showPasswordLogin = true;
  }
</script>

<svelte:head>
  <title>Вход - Family Budget</title>
</svelte:head>

<div class="min-h-screen bg-gradient-to-br from-slate-50 to-slate-100 flex items-center justify-center p-4">
  {#if showPasswordLogin}
    <PasswordLogin onSwitchToTelegram={handleSwitchToTelegram} />
  {:else}
    <Card class="max-w-md w-full p-8 space-y-6">
      <div class="text-center">
        <h1 class="text-3xl font-bold text-gray-900 mb-2">
          💰 Family Budget
        </h1>
        <p class="text-gray-600">
          Управление семейным бюджетом
        </p>
      </div>

      <div class="space-y-4">
        <h2 class="text-xl font-semibold text-center text-gray-800">
          Войти в систему
        </h2>
        
        <p class="text-sm text-gray-600 text-center">
          Используйте Telegram для быстрого и безопасного входа
        </p>
        
        <div class="flex justify-center">
          <TelegramLoginButton
            botName="familybudget_test_bot"
            buttonSize="large"
            showAvatar={true}
          />
        </div>

        {#if passwordAuthEnabled && !loading}
          <div class="mt-6">
            <div class="relative">
              <div class="absolute inset-0 flex items-center">
                <div class="w-full border-t border-gray-300"></div>
              </div>
              <div class="relative flex justify-center text-sm">
                <span class="px-2 bg-white text-gray-500">Или</span>
              </div>
            </div>
            
            <div class="mt-6">
              <Button
                variant="outline"
                class="w-full"
                on:click={handleSwitchToPassword}
              >
                Войти с логином и паролем
              </Button>
            </div>
          </div>
        {/if}
      </div>
      
      <div class="text-xs text-gray-500 text-center">
        <p>
          Нажимая кнопку входа, вы соглашаетесь с использованием данных Telegram
          для аутентификации в системе Family Budget.
        </p>
      </div>
    </Card>
  {/if}
</div>

// frontend/src/pages/Login/index.tsx
import React, { useEffect, useState } from 'react';
import { Navigate, useNavigate } from 'react-router-dom';
import { useAuthStore } from '../../stores/authStore';
import { TelegramLoginButton } from '../../components/auth/TelegramLoginButton';
import { authService } from '../../services/authService';

const LoginPage: React.FC = () => {
  const isAuthenticated = useAuthStore((state) => state.isAuthenticated);
  const error = useAuthStore((state) => state.error);
  const navigate = useNavigate();
  const [passwordAuthEnabled, setPasswordAuthEnabled] = useState(false);

  useEffect(() => {
    // Check if password auth is enabled
    authService.checkPasswordAuthEnabled()
      .then(response => setPasswordAuthEnabled(response.enabled))
      .catch(console.error);
  }, []);

  // If already authenticated, redirect to dashboard
  if (isAuthenticated) {
    return <Navigate to="/dashboard" replace />;
  }

  const botName = import.meta.env.VITE_TELEGRAM_BOT_NAME || 'YourBotName';

  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-50">
      <div className="max-w-md w-full space-y-8">
        <div>
          <h2 className="mt-6 text-center text-3xl font-extrabold text-gray-900">
            Вход в систему
          </h2>
          <p className="mt-2 text-center text-sm text-gray-600">
            Используйте свой Telegram аккаунт для входа
          </p>
        </div>
        
        <div className="mt-8 space-y-6">
          {error && (
            <div className="rounded-md bg-red-50 p-4">
              <div className="text-sm text-red-800">{error}</div>
            </div>
          )}
          
          <div className="flex justify-center">
            <TelegramLoginButton
              botName={botName}
              buttonSize="large"
              cornerRadius={20}
              showAvatar={true}
            />
          </div>
          
          <div className="text-center text-sm text-gray-500">
            <p>После входа через Telegram вы будете перенаправлены в личный кабинет</p>
          </div>
          
          {passwordAuthEnabled && (
            <div className="mt-6">
              <div className="relative">
                <div className="absolute inset-0 flex items-center">
                  <div className="w-full border-t border-gray-300" />
                </div>
                <div className="relative flex justify-center text-sm">
                  <span className="px-2 bg-gray-50 text-gray-500">Или</span>
                </div>
              </div>
              
              <div className="mt-6">
                <button
                  onClick={() => navigate('/login/password')}
                  className="w-full flex justify-center py-2 px-4 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500"
                >
                  Войти с логином и паролем
                </button>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default LoginPage;
