// frontend-svelte/src/lib/components/fact/FactForm.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { currentUser } from '$lib/stores/auth.store';
  import { 
    periodStore, 
    financialCenterStore, 
    costCenterStore, 
    nomenclatureStore 
  } from '$lib/stores/referenceData.store';
  import { useToast } from '$lib/stores/toast.store';
  import { registryService, type CreateRegistryData } from '$lib/services/registry.service';
  import Card from '$lib/components/ui/Card.svelte';
  import Input from '$lib/components/ui/Input.svelte';
  import Button from '$lib/components/ui/Button.svelte';
  import Loading from '$lib/components/common/Loading.svelte';
  import { 
    CreditCard, 
    Calendar, 
    Building, 
    Tag, 
    DollarSign, 
    MessageSquare, 
    Check,
    RotateCcw,
    Loader2
  } from 'lucide-svelte';

  export let onSuccess: (() => void) | undefined = undefined;

  let isSubmitting = false;
  let loading = true;
  let useCostCenter = false;

  // Form data
  let formData = {
    operation_dttm: new Date().toISOString().split('T')[0],
    period_id: '',
    financial_center_id: '',
    cost_center_id: '',
    nomenclature_id: '',
    cost_sum: '',
    comment_description: ''
  };

  // Form errors
  let errors: Record<string, string> = {};

  const toast = useToast();

  onMount(async () => {
    try {
      // Load reference data if not already loaded
      if ($periodStore.length === 0) {
        await periodStore.load($currentUser?.user_id || 0);
      }
      if ($financialCenterStore.length === 0) {
        await financialCenterStore.load($currentUser?.user_id || 0);
      }
      if ($costCenterStore.length === 0) {
        await costCenterStore.load($currentUser?.user_id || 0);
      }
      if ($nomenclatureStore.length === 0) {
        await nomenclatureStore.load($currentUser?.user_id || 0);
      }
    } catch (error: any) {
      console.error('Ошибка загрузки данных:', error);
      toast.error('Ошибка', 'Не удалось загрузить справочники');
    } finally {
      loading = false;
    }
  });

  function validateForm(): boolean {
    errors = {};

    if (!formData.operation_dttm) {
      errors.operation_dttm = 'Дата операции обязательна';
    }

    if (!formData.period_id) {
      errors.period_id = 'Выберите период';
    }

    if (!formData.financial_center_id) {
      errors.financial_center_id = 'Выберите финансовый центр';
    }

    if (!formData.nomenclature_id) {
      errors.nomenclature_id = 'Выберите номенклатуру';
    }

    if (!formData.cost_sum) {
      errors.cost_sum = 'Сумма обязательна';
    } else {
      const amount = parseFloat(formData.cost_sum);
      if (isNaN(amount) || amount <= 0) {
        errors.cost_sum = 'Сумма должна быть больше 0';
      }
    }

    if (useCostCenter && !formData.cost_center_id) {
      errors.cost_center_id = 'Выберите МВЗ';
    }

    return Object.keys(errors).length === 0;
  }

  async function handleSubmit() {
    if (!validateForm()) {
      return;
    }

    isSubmitting = true;

    try {
      const payload: CreateRegistryData = {
        operation_dttm: formData.operation_dttm,
        period_id: parseInt(formData.period_id),
        financial_center_id: parseInt(formData.financial_center_id),
        cost_center_id: useCostCenter ? parseInt(formData.cost_center_id) : undefined,
        nomenclature_id: parseInt(formData.nomenclature_id),
        cost_sum: parseFloat(formData.cost_sum),
        comment_description: formData.comment_description || undefined,
        row_type_id: 1, // Факт
      };

      await registryService.create(payload);
      toast.success('Успешно', 'Расход добавлен');
      resetForm();
      onSuccess?.();
    } catch (error: any) {
      console.error('Ошибка при добавлении расхода:', error);
      toast.error('Ошибка', error.message || 'Не удалось добавить расход');
    } finally {
      isSubmitting = false;
    }
  }

  function resetForm() {
    formData = {
      operation_dttm: new Date().toISOString().split('T')[0],
      period_id: '',
      financial_center_id: '',
      cost_center_id: '',
      nomenclature_id: '',
      cost_sum: '',
      comment_description: ''
    };
    useCostCenter = false;
    errors = {};
  }
</script>

{#if loading}
  <div class="flex justify-center items-center min-h-[400px]">
    <Loading size="large" text="Загрузка формы..." />
  </div>
{:else}
  <Card class="border-l-4 border-l-blue-500 max-w-2xl mx-auto">
    <div class="bg-gradient-to-r from-blue-50 to-purple-50 p-6 border-b">
      <div class="flex items-center gap-3 mb-2">
        <div class="h-12 w-12 bg-blue-100 rounded-full flex items-center justify-center">
          <CreditCard class="h-6 w-6 text-blue-600" />
        </div>
        <div>
          <h2 class="text-xl font-bold text-slate-900">Добавить операцию</h2>
          <p class="text-sm text-slate-600">Внесите информацию о расходе или доходе</p>
        </div>
      </div>
    </div>

    <div class="p-6">
      <form on:submit|preventDefault={handleSubmit} class="space-y-6">
        <!-- Date and Period -->
        <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div class="space-y-2">
            <label for="operation_dttm" class="flex items-center gap-2 text-sm font-medium text-slate-700">
              <Calendar class="h-4 w-4" />
              Дата операции
            </label>
            <Input
              id="operation_dttm"
              type="date"
              bind:value={formData.operation_dttm}
              class={errors.operation_dttm ? 'border-red-300' : ''}
            />
            {#if errors.operation_dttm}
              <p class="text-sm text-red-600">{errors.operation_dttm}</p>
            {/if}
          </div>

          <div class="space-y-2">
            <label for="period_id" class="text-sm font-medium text-slate-700">Период</label>
            <select
              id="period_id"
              bind:value={formData.period_id}
              class="w-full px-3 py-2 border border-slate-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent {errors.period_id ? 'border-red-300' : ''}"
            >
              <option value="">Выберите период</option>
              {#each $periodStore as period}
                <option value={period.period_id.toString()}>{period.period_ru_name}</option>
              {/each}
            </select>
            {#if errors.period_id}
              <p class="text-sm text-red-600">{errors.period_id}</p>
            {/if}
          </div>
        </div>

        <!-- Financial Center -->
        <div class="space-y-2">
          <label for="financial_center_id" class="flex items-center gap-2 text-sm font-medium text-slate-700">
            <Building class="h-4 w-4" />
            Финансовый центр
          </label>
          <select
            id="financial_center_id"
            bind:value={formData.financial_center_id}
            class="w-full px-3 py-2 border border-slate-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent {errors.financial_center_id ? 'border-red-300' : ''}"
          >
            <option value="">Выберите финансовый центр</option>
            {#each $financialCenterStore as fc}
              <option value={fc.financial_center_id.toString()}>{fc.financial_center_name}</option>
            {/each}
          </select>
          {#if errors.financial_center_id}
            <p class="text-sm text-red-600">{errors.financial_center_id}</p>
          {/if}
        </div>

        <!-- Nomenclature -->
        <div class="space-y-2">
          <label for="nomenclature_id" class="flex items-center gap-2 text-sm font-medium text-slate-700">
            <Tag class="h-4 w-4" />
            Номенклатура
          </label>
          <select
            id="nomenclature_id"
            bind:value={formData.nomenclature_id}
            class="w-full px-3 py-2 border border-slate-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent {errors.nomenclature_id ? 'border-red-300' : ''}"
          >
            <option value="">Выберите номенклатуру</option>
            {#each $nomenclatureStore as nom}
              <option value={nom.nomenclature_id.toString()}>{nom.nomenclature_name}</option>
            {/each}
          </select>
          {#if errors.nomenclature_id}
            <p class="text-sm text-red-600">{errors.nomenclature_id}</p>
          {/if}
        </div>

        <!-- Cost Center Toggle -->
        <div class="flex items-center space-x-3 p-4 border rounded-md bg-slate-50">
          <input
            type="checkbox"
            id="useCostCenter"
            bind:checked={useCostCenter}
            class="h-4 w-4 rounded border-slate-300 text-blue-600 focus:ring-blue-500"
          />
          <div class="space-y-1 leading-none">
            <label for="useCostCenter" class="text-sm font-medium text-slate-700 cursor-pointer">
              Использовать МВЗ
            </label>
            <p class="text-xs text-slate-500">
              Добавить место возникновения затрат к операции
            </p>
          </div>
        </div>

        <!-- Cost Center -->
        {#if useCostCenter}
          <div class="space-y-2">
            <label for="cost_center_id" class="text-sm font-medium text-slate-700">
              Место возникновения затрат (МВЗ)
            </label>
            <select
              id="cost_center_id"
              bind:value={formData.cost_center_id}
              class="w-full px-3 py-2 border border-slate-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent {errors.cost_center_id ? 'border-red-300' : ''}"
            >
              <option value="">Выберите МВЗ</option>
              {#each $costCenterStore as cc}
                <option value={cc.cost_center_id.toString()}>{cc.cost_center_name}</option>
              {/each}
            </select>
            {#if errors.cost_center_id}
              <p class="text-sm text-red-600">{errors.cost_center_id}</p>
            {/if}
          </div>
        {/if}

        <!-- Amount -->
        <div class="space-y-2">
          <label for="cost_sum" class="flex items-center gap-2 text-sm font-medium text-slate-700">
            <DollarSign class="h-4 w-4" />
            Сумма
          </label>
          <Input
            id="cost_sum"
            type="number"
            step="0.01"
            min="0"
            placeholder="0.00"
            bind:value={formData.cost_sum}
            class={errors.cost_sum ? 'border-red-300' : ''}
          />
          <p class="text-xs text-slate-500">Введите сумму расхода в рублях</p>
          {#if errors.cost_sum}
            <p class="text-sm text-red-600">{errors.cost_sum}</p>
          {/if}
        </div>

        <!-- Comment -->
        <div class="space-y-2">
          <label for="comment_description" class="flex items-center gap-2 text-sm font-medium text-slate-700">
            <MessageSquare class="h-4 w-4" />
            Комментарий
          </label>
          <textarea
            id="comment_description"
            rows="3"
            bind:value={formData.comment_description}
            placeholder="Дополнительная информация о расходе..."
            class="w-full px-3 py-2 border border-slate-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent resize-none"
          ></textarea>
          <p class="text-xs text-slate-500">Опциональное описание операции</p>
        </div>

        <!-- Action Buttons -->
        <div class="flex gap-3 pt-4">
          <Button
            type="submit"
            disabled={isSubmitting}
            class="flex-1 bg-blue-600 hover:bg-blue-700 text-white flex items-center justify-center gap-2"
          >
            {#if isSubmitting}
              <Loader2 class="h-4 w-4 animate-spin" />
              Добавление...
            {:else}
              <Check class="h-4 w-4" />
              Добавить расход
            {/if}
          </Button>
          <Button
            type="button"
            on:click={resetForm}
            disabled={isSubmitting}
            class="bg-slate-500 hover:bg-slate-600 text-white flex items-center justify-center gap-2"
          >
            <RotateCcw class="h-4 w-4" />
            Очистить
          </Button>
        </div>
      </form>
    </div>
  </Card>
{/if}

// frontend/src/components/fact/FactForm.tsx
import React, { useState, useEffect } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import * as z from 'zod';
import { 
  Card, 
  CardContent, 
  CardHeader, 
  CardTitle,
  CardDescription 
} from '../ui/card';
import { 
  Form,
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '../ui/form';
import { Input } from '../ui/input';
import { 
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '../ui/select';
import { Button } from '../ui/button';
import { useToast } from '../common/ToastContainer';
import { 
  periodService, 
  financialCenterService, 
  costCenterService, 
  nomenclatureService,
  registryService,
  type CreateRegistryData 
} from '../../services';
import type { Period, FinancialCenter, CostCenter, Nomenclature } from '../../types';
import { 
  CreditCard, 
  Calendar, 
  Building,
  Tag,
  DollarSign,
  MessageSquare,
  Loader2,
  Check
} from 'lucide-react';

interface FactFormProps {
  onSuccess?: () => void;
}

const formSchema = z.object({
  operation_dttm: z.string().min(1, "Дата операции обязательна"),
  period_id: z.string().min(1, "Выберите период"),
  financial_center_id: z.string().min(1, "Выберите финансовый центр"),
  cost_center_id: z.string().optional(),
  nomenclature_id: z.string().min(1, "Выберите номенклатуру"),
  cost_sum: z.string()
    .min(1, "Сумма обязательна")
    .refine((val) => !isNaN(Number(val)) && Number(val) > 0, "Сумма должна быть больше 0"),
  comment_description: z.string().optional(),
  use_cost_center: z.boolean().optional(),
});

type FactFormData = z.infer<typeof formSchema>;

export const FactForm: React.FC<FactFormProps> = ({ onSuccess }) => {
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [periods, setPeriods] = useState<Period[]>([]);
  const [financialCenters, setFinancialCenters] = useState<FinancialCenter[]>([]);
  const [costCenters, setCostCenters] = useState<CostCenter[]>([]);
  const [nomenclatures, setNomenclatures] = useState<Nomenclature[]>([]);
  
  const toast = useToast();
  
  const form = useForm<FactFormData>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      operation_dttm: new Date().toISOString().split('T')[0],
      use_cost_center: false,
      comment_description: "",
    },
  });


  useEffect(() => {
    loadInitialData();
  }, []);

  const loadInitialData = async () => {
    try {
      // Загрузка справочников через сервисы
      const [periodsData, fcData, ccData, nomenclatureData] = await Promise.all([
        periodService.getAll(),
        financialCenterService.getAll(),
        costCenterService.getAll(),
        nomenclatureService.getAll(),
      ]);

      setPeriods(periodsData);
      setFinancialCenters(fcData);
      setCostCenters(ccData);
      setNomenclatures(nomenclatureData);
    } catch (error) {
      console.error('Ошибка загрузки данных:', error);
      toast.error('Ошибка', 'Не удалось загрузить справочники');
    }
  };

  const onSubmit = async (data: FactFormData) => {
    setIsSubmitting(true);
    
    try {
      const payload: CreateRegistryData = {
        operation_dttm: data.operation_dttm,
        period_id: parseInt(data.period_id),
        financial_center_id: parseInt(data.financial_center_id),
        cost_center_id: data.use_cost_center && data.cost_center_id ? parseInt(data.cost_center_id) : undefined,
        nomenclature_id: parseInt(data.nomenclature_id),
        cost_sum: parseFloat(data.cost_sum),
        comment_description: data.comment_description,
        row_type_id: 1, // Факт
      };

      await registryService.create(payload);
      toast.success('Успешно', 'Расход добавлен');
      form.reset();
      onSuccess?.();
    } catch (error) {
      console.error('Ошибка при добавлении расхода:', error);
      toast.error('Ошибка', error instanceof Error ? error.message : 'Не удалось добавить расход');
    } finally {
      setIsSubmitting(false);
    }
  };

  const useCostCenter = form.watch("use_cost_center");

  return (
    <Card className="border-l-4 border-l-blue-500">
      <CardHeader className="bg-gradient-to-r from-blue-50 to-purple-50">
        <CardTitle className="flex items-center gap-2">
          <div className="h-10 w-10 bg-blue-100 rounded-full flex items-center justify-center">
            <CreditCard className="h-5 w-5 text-blue-600" />
          </div>
          Добавить операцию
        </CardTitle>
        <CardDescription>
          Внесите информацию о расходе или доходе
        </CardDescription>
      </CardHeader>
      
      <CardContent>
        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <FormField
                control={form.control}
                name="operation_dttm"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel className="flex items-center gap-2">
                      <Calendar className="h-4 w-4" />
                      Дата операции
                    </FormLabel>
                    <FormControl>
                      <Input type="date" {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              
              <FormField
                control={form.control}
                name="period_id"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Период</FormLabel>
                    <Select onValueChange={field.onChange} defaultValue={field.value}>
                      <FormControl>
                        <SelectTrigger>
                          <SelectValue placeholder="Выберите период" />
                        </SelectTrigger>
                      </FormControl>
                      <SelectContent>
                        {periods.map(period => (
                          <SelectItem key={period.period_id} value={period.period_id.toString()}>
                            {period.period_ru_name}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>

            <FormField
              control={form.control}
              name="financial_center_id"
              render={({ field }) => (
                <FormItem>
                  <FormLabel className="flex items-center gap-2">
                    <Building className="h-4 w-4" />
                    Финансовый центр
                  </FormLabel>
                  <Select onValueChange={field.onChange} defaultValue={field.value}>
                    <FormControl>
                      <SelectTrigger>
                        <SelectValue placeholder="Выберите финансовый центр" />
                      </SelectTrigger>
                    </FormControl>
                    <SelectContent>
                      {financialCenters.map(fc => (
                        <SelectItem key={fc.financial_center_id} value={fc.financial_center_id.toString()}>
                          {fc.financial_center_name}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                  <FormMessage />
                </FormItem>
              )}
            />

            <FormField
              control={form.control}
              name="nomenclature_id"
              render={({ field }) => (
                <FormItem>
                  <FormLabel className="flex items-center gap-2">
                    <Tag className="h-4 w-4" />
                    Номенклатура
                  </FormLabel>
                  <Select onValueChange={field.onChange} defaultValue={field.value}>
                    <FormControl>
                      <SelectTrigger>
                        <SelectValue placeholder="Выберите номенклатуру" />
                      </SelectTrigger>
                    </FormControl>
                    <SelectContent>
                      {nomenclatures.map(nom => (
                        <SelectItem key={nom.nomenclature_id} value={nom.nomenclature_id.toString()}>
                          {nom.nomenclature_name}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                  <FormMessage />
                </FormItem>
              )}
            />

            <FormField
              control={form.control}
              name="use_cost_center"
              render={({ field }) => (
                <FormItem className="flex flex-row items-center space-x-3 space-y-0 rounded-md border p-4">
                  <FormControl>
                    <input
                      type="checkbox"
                      checked={field.value}
                      onChange={field.onChange}
                      className="h-4 w-4 rounded border-gray-300 text-blue-600 focus:ring-blue-500"
                    />
                  </FormControl>
                  <div className="space-y-1 leading-none">
                    <FormLabel className="text-sm font-medium">
                      Использовать МВЗ
                    </FormLabel>
                    <FormDescription>
                      Добавить место возникновения затрат к операции
                    </FormDescription>
                  </div>
                </FormItem>
              )}
            />

            {useCostCenter && (
              <FormField
                control={form.control}
                name="cost_center_id"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Место возникновения затрат (МВЗ)</FormLabel>
                    <Select onValueChange={field.onChange} defaultValue={field.value}>
                      <FormControl>
                        <SelectTrigger>
                          <SelectValue placeholder="Выберите МВЗ" />
                        </SelectTrigger>
                      </FormControl>
                      <SelectContent>
                        {costCenters.map(cc => (
                          <SelectItem key={cc.cost_center_id} value={cc.cost_center_id.toString()}>
                            {cc.cost_center_name}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                    <FormMessage />
                  </FormItem>
                )}
              />
            )}

            <FormField
              control={form.control}
              name="cost_sum"
              render={({ field }) => (
                <FormItem>
                  <FormLabel className="flex items-center gap-2">
                    <DollarSign className="h-4 w-4" />
                    Сумма
                  </FormLabel>
                  <FormControl>
                    <Input 
                      type="number" 
                      step="0.01" 
                      min="0" 
                      placeholder="0.00"
                      {...field} 
                    />
                  </FormControl>
                  <FormDescription>
                    Введите сумму расхода в рублях
                  </FormDescription>
                  <FormMessage />
                </FormItem>
              )}
            />

            <FormField
              control={form.control}
              name="comment_description"
              render={({ field }) => (
                <FormItem>
                  <FormLabel className="flex items-center gap-2">
                    <MessageSquare className="h-4 w-4" />
                    Комментарий
                  </FormLabel>
                  <FormControl>
                    <textarea
                      className="flex min-h-[80px] w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
                      placeholder="Дополнительная информация о расходе..."
                      {...field}
                    />
                  </FormControl>
                  <FormDescription>
                    Опциональное описание операции
                  </FormDescription>
                  <FormMessage />
                </FormItem>
              )}
            />

            <div className="flex gap-3 pt-4">
              <Button
                type="submit"
                disabled={isSubmitting}
                className="flex-1"
              >
                {isSubmitting ? (
                  <>
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    Добавление...
                  </>
                ) : (
                  <>
                    <Check className="mr-2 h-4 w-4" />
                    Добавить расход
                  </>
                )}
              </Button>
              <Button
                type="button"
                variant="outline"
                onClick={() => form.reset()}
                disabled={isSubmitting}
              >
                Очистить
              </Button>
            </div>
          </form>
        </Form>
      </CardContent>
    </Card>
  );
};
