// frontend-svelte/src/lib/components/common/NotificationDropdown.svelte
<script lang="ts">
  import { Bell } from 'lucide-svelte';
  import Button from '$lib/components/ui/Button.svelte';
  import Badge from '$lib/components/ui/Badge.svelte';
  
  let isOpen = false;
  let notifications = [
    {
      id: 1,
      title: 'Добро пожаловать!',
      message: 'Система готова к использованию',
      time: '5 мин назад',
      unread: true
    }
  ];
  
  $: unreadCount = notifications.filter(n => n.unread).length;
  
  function toggleDropdown() {
    isOpen = !isOpen;
  }
  
  function closeDropdown() {
    isOpen = false;
  }
  
  function markAsRead(id: number) {
    notifications = notifications.map(n => 
      n.id === id ? { ...n, unread: false } : n
    );
  }
</script>

<div class="relative">
  <Button
    variant="ghost"
    size="icon"
    on:click={toggleDropdown}
    class="relative"
    title="Уведомления"
  >
    <Bell class="h-5 w-5" />
    {#if unreadCount > 0}
      <Badge 
        variant="destructive" 
        class="absolute -top-2 -right-2 h-5 w-5 flex items-center justify-center p-0 text-xs"
      >
        {unreadCount}
      </Badge>
    {/if}
  </Button>
  
  {#if isOpen}
    <!-- Backdrop -->
    <div 
      class="fixed inset-0 z-10" 
      on:click={closeDropdown}
      on:keydown={(e) => e.key === 'Escape' && closeDropdown()}
      role="button"
      tabindex="-1"
    ></div>
    
    <!-- Dropdown -->
    <div class="absolute right-0 mt-2 w-80 z-20 bg-white rounded-lg shadow-lg border border-gray-200">
      <div class="p-4 border-b border-gray-200">
        <h3 class="text-lg font-medium">Уведомления</h3>
      </div>
      
      <div class="max-h-96 overflow-y-auto">
        {#if notifications.length === 0}
          <div class="p-4 text-center text-gray-500">
            Нет уведомлений
          </div>
        {:else}
          {#each notifications as notification (notification.id)}
            <div 
              class="p-4 border-b border-gray-100 hover:bg-gray-50 cursor-pointer"
              on:click={() => markAsRead(notification.id)}
              on:keydown={(e) => e.key === 'Enter' && markAsRead(notification.id)}
              role="button"
              tabindex="0"
            >
              <div class="flex items-start justify-between">
                <div class="flex-1">
                  <div class="flex items-center">
                    <h4 class="font-medium text-sm">{notification.title}</h4>
                    {#if notification.unread}
                      <div class="w-2 h-2 bg-blue-500 rounded-full ml-2"></div>
                    {/if}
                  </div>
                  <p class="text-sm text-gray-600 mt-1">{notification.message}</p>
                  <p class="text-xs text-gray-400 mt-1">{notification.time}</p>
                </div>
              </div>
            </div>
          {/each}
        {/if}
      </div>
      
      {#if notifications.some(n => n.unread)}
        <div class="p-4 border-t border-gray-200">
          <Button 
            variant="ghost" 
            size="sm" 
            class="w-full"
            on:click={() => {
              notifications = notifications.map(n => ({ ...n, unread: false }));
            }}
          >
            Отметить все как прочитанные
          </Button>
        </div>
      {/if}
    </div>
  {/if}
</div>

// frontend/src/components/common/NotificationDropdown.tsx
import React, { useState } from 'react';
import { Bell, X, Clock, CheckCircle, AlertTriangle, Info } from 'lucide-react';
import { Button } from '../ui/button';
import { Badge } from '../ui/badge';
import { Card, CardContent, CardHeader, CardTitle } from '../ui/card';

interface Notification {
  id: string;
  type: 'info' | 'success' | 'warning' | 'error';
  title: string;
  message: string;
  time: string;
  isRead: boolean;
}

// Мок данные для демонстрации
const mockNotifications: Notification[] = [
  {
    id: '1',
    type: 'info',
    title: 'Новый продукт добавлен',
    message: 'Продукт "Молоко 3.2%" был добавлен в каталог',
    time: '5 минут назад',
    isRead: false,
  },
  {
    id: '2',
    type: 'warning',
    title: 'Превышен бюджет',
    message: 'Расходы на категорию "Продукты" превысили плановый бюджет на 15%',
    time: '1 час назад',
    isRead: false,
  },
  {
    id: '3',
    type: 'success',
    title: 'Отчет сформирован',
    message: 'Месячный отчет по расходам успешно сформирован и готов к экспорту',
    time: '2 часа назад',
    isRead: true,
  },
];

export const NotificationDropdown: React.FC = () => {
  const [isOpen, setIsOpen] = useState(false);
  const [notifications, setNotifications] = useState<Notification[]>(mockNotifications);

  const unreadCount = notifications.filter(n => !n.isRead).length;

  const getTypeIcon = (type: Notification['type']) => {
    switch (type) {
      case 'success':
        return <CheckCircle className="h-4 w-4 text-green-600" />;
      case 'warning':
        return <AlertTriangle className="h-4 w-4 text-yellow-600" />;
      case 'error':
        return <X className="h-4 w-4 text-red-600" />;
      default:
        return <Info className="h-4 w-4 text-blue-600" />;
    }
  };

  const getTypeColor = (type: Notification['type']) => {
    switch (type) {
      case 'success':
        return 'bg-green-50 border-green-200';
      case 'warning':
        return 'bg-yellow-50 border-yellow-200';
      case 'error':
        return 'bg-red-50 border-red-200';
      default:
        return 'bg-blue-50 border-blue-200';
    }
  };

  const markAsRead = (id: string) => {
    setNotifications(prev =>
      prev.map(n => n.id === id ? { ...n, isRead: true } : n)
    );
  };

  const markAllAsRead = () => {
    setNotifications(prev =>
      prev.map(n => ({ ...n, isRead: true }))
    );
  };

  const deleteNotification = (id: string) => {
    setNotifications(prev => prev.filter(n => n.id !== id));
  };

  return (
    <div className="relative">
      <Button 
        variant="ghost" 
        size="icon" 
        className="relative"
        onClick={() => setIsOpen(!isOpen)}
      >
        <Bell className="h-5 w-5" />
        {unreadCount > 0 && (
          <Badge className="absolute -top-1 -right-1 h-5 w-5 p-0 flex items-center justify-center text-xs bg-red-500 hover:bg-red-500">
            {unreadCount}
          </Badge>
        )}
      </Button>

      {isOpen && (
        <>
          {/* Backdrop */}
          <div
            className="fixed inset-0 z-40"
            onClick={() => setIsOpen(false)}
          />
          
          {/* Dropdown */}
          <div className="absolute right-0 top-full mt-2 z-50">
            <Card className="w-96 max-h-96 overflow-hidden shadow-lg">
              <CardHeader className="pb-3">
                <div className="flex items-center justify-between">
                  <CardTitle className="text-lg">Уведомления</CardTitle>
                  <div className="flex items-center gap-2">
                    {unreadCount > 0 && (
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={markAllAsRead}
                        className="text-xs"
                      >
                        Прочитать все
                      </Button>
                    )}
                    <Button
                      variant="ghost"
                      size="icon"
                      onClick={() => setIsOpen(false)}
                      className="h-6 w-6"
                    >
                      <X className="h-4 w-4" />
                    </Button>
                  </div>
                </div>
              </CardHeader>
              
              <CardContent className="p-0">
                <div className="max-h-80 overflow-y-auto">
                  {notifications.length === 0 ? (
                    <div className="p-6 text-center text-gray-500">
                      <Bell className="h-8 w-8 mx-auto mb-2 text-gray-400" />
                      <p>Нет уведомлений</p>
                    </div>
                  ) : (
                    <div className="divide-y">
                      {notifications.map((notification) => (
                        <div
                          key={notification.id}
                          className={`p-4 transition-colors hover:bg-gray-50 ${
                            !notification.isRead ? 'bg-blue-25' : ''
                          }`}
                          onClick={() => !notification.isRead && markAsRead(notification.id)}
                        >
                          <div className="flex items-start gap-3">
                            <div className="flex-shrink-0 mt-0.5">
                              {getTypeIcon(notification.type)}
                            </div>
                            
                            <div className="flex-1 min-w-0">
                              <div className="flex items-start justify-between gap-2">
                                <div className="flex-1">
                                  <p className={`text-sm font-medium ${
                                    !notification.isRead ? 'text-gray-900' : 'text-gray-600'
                                  }`}>
                                    {notification.title}
                                  </p>
                                  <p className="text-sm text-gray-500 mt-1">
                                    {notification.message}
                                  </p>
                                  <div className="flex items-center gap-2 mt-2">
                                    <Clock className="h-3 w-3 text-gray-400" />
                                    <span className="text-xs text-gray-400">
                                      {notification.time}
                                    </span>
                                    {!notification.isRead && (
                                      <div className="h-2 w-2 bg-blue-600 rounded-full" />
                                    )}
                                  </div>
                                </div>
                                
                                <Button
                                  variant="ghost"
                                  size="icon"
                                  onClick={(e) => {
                                    e.stopPropagation();
                                    deleteNotification(notification.id);
                                  }}
                                  className="h-6 w-6 text-gray-400 hover:text-gray-600"
                                >
                                  <X className="h-3 w-3" />
                                </Button>
                              </div>
                            </div>
                          </div>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              </CardContent>
            </Card>
          </div>
        </>
      )}
    </div>
  );
};
