// frontend-svelte/src/lib/components/charts/core/ChartContainer.svelte
<script lang="ts">
  import { onMount, createEventDispatcher } from 'svelte';
  import Card from '$lib/components/ui/Card.svelte';
  import Button from '$lib/components/ui/Button.svelte';
  import { Download, RefreshCw, Settings } from 'lucide-svelte';
  import { chartExport } from '$lib/utils/charts/export';
  
  const dispatch = createEventDispatcher<{
    export: { format: 'png' | 'svg' };
    refresh: void;
    settingsToggle: void;
  }>();

  export let title = '';
  export let subtitle = '';
  export let height = 400;
  export let className = '';
  export let loading = false;
  export let error: string | null = null;
  export let exportable = true;
  export let refreshable = false;
  export let showSettings = false;
  export let borderColor = 'border-l-blue-500';
  
  let containerRef: HTMLDivElement;
  let chartRef: HTMLCanvasElement | undefined;

  // Export functionality
  async function handleExport(format: 'png' | 'svg') {
    if (!chartRef) return;
    
    try {
      await chartExport(chartRef, title || 'chart', format);
      dispatch('export', { format });
    } catch (err) {
      console.error('Export failed:', err);
    }
  }

  function handleRefresh() {
    dispatch('refresh');
  }

  function handleSettingsToggle() {
    dispatch('settingsToggle');
  }

  // Expose chart reference for child components
  export function setChartRef(ref: HTMLCanvasElement) {
    chartRef = ref;
  }
</script>

<Card class="border-l-4 {borderColor} {className}">
  <!-- Header -->
  {#if title || subtitle || exportable || refreshable || showSettings}
    <div class="bg-gradient-to-r from-slate-50 to-slate-100 p-4 border-b">
      <div class="flex items-center justify-between">
        <div class="flex-1">
          {#if title}
            <h2 class="text-lg font-semibold text-slate-900">{title}</h2>
          {/if}
          {#if subtitle}
            <p class="text-sm text-slate-600 mt-1">{subtitle}</p>
          {/if}
        </div>

        <!-- Controls -->
        <div class="flex items-center gap-2">
          <slot name="controls" />
          
          {#if showSettings}
            <Button
              variant="outline"
              size="sm"
              on:click={handleSettingsToggle}
              class="text-xs"
            >
              <Settings class="h-4 w-4" />
            </Button>
          {/if}
          
          {#if refreshable}
            <Button
              variant="outline"
              size="sm"
              on:click={handleRefresh}
              class="text-xs"
            >
              <RefreshCw class="h-4 w-4" />
            </Button>
          {/if}
          
          {#if exportable}
            <div class="flex gap-1">
              <Button
                variant="outline"
                size="sm"
                on:click={() => handleExport('png')}
                class="text-xs"
                title="Экспорт в PNG"
              >
                <Download class="h-4 w-4" />
                PNG
              </Button>
              <Button
                variant="outline"
                size="sm"
                on:click={() => handleExport('svg')}
                class="text-xs"
                title="Экспорт в SVG"
              >
                <Download class="h-4 w-4" />
                SVG
              </Button>
            </div>
          {/if}
        </div>
      </div>
    </div>
  {/if}

  <!-- Content -->
  <div class="p-6" bind:this={containerRef}>
    {#if loading}
      <div class="flex justify-center items-center py-12" style="height: {height}px;">
        <div class="animate-spin h-8 w-8 border-2 border-blue-600 border-t-transparent rounded-full"></div>
        <span class="ml-3 text-slate-600">Загрузка данных...</span>
      </div>
    {:else if error}
      <div class="flex flex-col justify-center items-center py-12 text-center" style="height: {height}px;">
        <div class="h-16 w-16 bg-red-100 rounded-full flex items-center justify-center mb-4">
          <svg class="h-8 w-8 text-red-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
          </svg>
        </div>
        <h3 class="text-lg font-medium text-slate-900 mb-2">Ошибка загрузки</h3>
        <p class="text-slate-600">{error}</p>
      </div>
    {:else}
      <div style="height: {height}px;" class="relative">
        <slot {chartRef} {setChartRef} />
      </div>
    {/if}
  </div>

  <!-- Footer slot for additional controls/info -->
  <slot name="footer" />
</Card>

// frontend/src/components/charts/core/ChartContainer.tsx
import React, { useRef, useState, useCallback, ReactNode } from 'react';
import { ResponsiveContainer } from 'recharts';
import { Download, Maximize2, Minimize2 } from 'lucide-react';
import { ChartTheme } from '../utils/ChartTheme';
import { exportChartAsPNG, exportChartAsSVG } from '../utils/chartExport';

interface ChartContainerProps {
  title?: string;
  subtitle?: string;
  children: ReactNode;
  height?: number | string;
  className?: string;
  loading?: boolean;
  error?: string | null;
  exportable?: boolean;
  fullscreenable?: boolean;
  controls?: ReactNode;
  footer?: ReactNode;
}

export const ChartContainer: React.FC<ChartContainerProps> = ({
  title,
  subtitle,
  children,
  height = ChartTheme.sizes.medium.height,
  className = '',
  loading = false,
  error = null,
  exportable = true,
  fullscreenable = true,
  controls,
  footer,
}) => {
  const chartRef = useRef<HTMLDivElement>(null);
  const [isFullscreen, setIsFullscreen] = useState(false);
  const [isExporting, setIsExporting] = useState(false);

  const handleExportPNG = useCallback(async () => {
    if (!chartRef.current || isExporting) return;
    
    setIsExporting(true);
    try {
      await exportChartAsPNG(chartRef.current, title || 'chart');
    } catch (error) {
      console.error('Failed to export chart as PNG:', error);
    } finally {
      setIsExporting(false);
    }
  }, [title, isExporting]);

  const handleExportSVG = useCallback(async () => {
    if (!chartRef.current || isExporting) return;
    
    setIsExporting(true);
    try {
      await exportChartAsSVG(chartRef.current, title || 'chart');
    } catch (error) {
      console.error('Failed to export chart as SVG:', error);
    } finally {
      setIsExporting(false);
    }
  }, [title, isExporting]);

  const toggleFullscreen = useCallback(() => {
    if (!chartRef.current) return;

    if (!isFullscreen) {
      // Enter fullscreen
      const elem = chartRef.current.parentElement;
      if (elem?.requestFullscreen) {
        elem.requestFullscreen();
      }
    } else {
      // Exit fullscreen
      if (document.exitFullscreen) {
        document.exitFullscreen();
      }
    }
    setIsFullscreen(!isFullscreen);
  }, [isFullscreen]);

  // Handle loading state
  if (loading) {
    return (
      <div className={`bg-white rounded-lg shadow p-6 ${className}`}>
        <div className="animate-pulse">
          {title && <div className="h-6 bg-gray-200 rounded w-1/3 mb-2"></div>}
          {subtitle && <div className="h-4 bg-gray-200 rounded w-1/2 mb-4"></div>}
          <div className="bg-gray-200 rounded" style={{ height }}></div>
        </div>
      </div>
    );
  }

  // Handle error state
  if (error) {
    return (
      <div className={`bg-white rounded-lg shadow p-6 ${className}`}>
        {title && <h3 className="text-lg font-semibold text-gray-900 mb-2">{title}</h3>}
        <div 
          className="flex items-center justify-center bg-red-50 border border-red-200 rounded-lg p-8"
          style={{ height }}
        >
          <div className="text-center">
            <p className="text-red-600 font-medium">Ошибка загрузки данных</p>
            <p className="text-red-500 text-sm mt-1">{error}</p>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className={`bg-white rounded-lg shadow ${className}`}>
      {/* Header */}
      {(title || subtitle || exportable || fullscreenable || controls) && (
        <div className="px-6 py-4 border-b border-gray-200">
          <div className="flex items-center justify-between">
            <div className="flex-1">
              {title && (
                <h3 className="text-lg font-semibold text-gray-900">{title}</h3>
              )}
              {subtitle && (
                <p className="text-sm text-gray-500 mt-1">{subtitle}</p>
              )}
            </div>
            
            <div className="flex items-center gap-2 ml-4">
              {controls}
              
              {exportable && (
                <div className="relative group">
                  <button
                    onClick={handleExportPNG}
                    disabled={isExporting}
                    className="p-2 text-gray-400 hover:text-gray-600 hover:bg-gray-100 rounded transition-colors disabled:opacity-50"
                    title="Экспорт графика"
                  >
                    <Download className="w-4 h-4" />
                  </button>
                  
                  {/* Export dropdown */}
                  <div className="absolute right-0 mt-1 w-32 bg-white rounded-md shadow-lg opacity-0 invisible group-hover:opacity-100 group-hover:visible transition-all duration-200 z-10">
                    <button
                      onClick={handleExportPNG}
                      className="block w-full text-left px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 rounded-t-md"
                    >
                      Экспорт PNG
                    </button>
                    <button
                      onClick={handleExportSVG}
                      className="block w-full text-left px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 rounded-b-md"
                    >
                      Экспорт SVG
                    </button>
                  </div>
                </div>
              )}
              
              {fullscreenable && (
                <button
                  onClick={toggleFullscreen}
                  className="p-2 text-gray-400 hover:text-gray-600 hover:bg-gray-100 rounded transition-colors"
                  title={isFullscreen ? 'Выйти из полноэкранного режима' : 'Полноэкранный режим'}
                >
                  {isFullscreen ? (
                    <Minimize2 className="w-4 h-4" />
                  ) : (
                    <Maximize2 className="w-4 h-4" />
                  )}
                </button>
              )}
            </div>
          </div>
        </div>
      )}
      
      {/* Chart content */}
      <div className="p-6" ref={chartRef}>
        <ResponsiveContainer width="100%" height={height}>
          {children}
        </ResponsiveContainer>
      </div>
      
      {/* Footer */}
      {footer && (
        <div className="px-6 py-4 border-t border-gray-200 bg-gray-50">
          {footer}
        </div>
      )}
    </div>
  );
};

// Loading skeleton component
export const ChartSkeleton: React.FC<{ height?: number | string }> = ({ 
  height = ChartTheme.sizes.medium.height 
}) => (
  <div className="bg-white rounded-lg shadow p-6">
    <div className="animate-pulse">
      <div className="h-6 bg-gray-200 rounded w-1/3 mb-4"></div>
      <div className="bg-gray-200 rounded" style={{ height }}></div>
    </div>
  </div>
);

// Empty state component
export const ChartEmpty: React.FC<{ 
  message?: string;
  height?: number | string;
}> = ({ 
  message = 'Нет данных для отображения',
  height = ChartTheme.sizes.medium.height 
}) => (
  <div 
    className="flex items-center justify-center bg-gray-50 rounded-lg border-2 border-dashed border-gray-300"
    style={{ height }}
  >
    <p className="text-gray-500">{message}</p>
  </div>
);

export default ChartContainer;
