// frontend-svelte/src/routes/(protected)/budget/+page.svelte
<script lang="ts">
  import Card from '$lib/components/ui/Card.svelte';
  import Button from '$lib/components/ui/Button.svelte';
  import { Calculator, Plus } from 'lucide-svelte';
</script>

<svelte:head>
  <title>Бюджет - Family Budget</title>
</svelte:head>

<div class="space-y-6">
  <div class="flex items-center justify-between">
    <div>
      <h1 class="text-3xl font-bold text-gray-900">Планирование бюджета</h1>
      <p class="text-gray-600 mt-1">Создание и управление планами расходов</p>
    </div>
    <Button>
      <Plus class="h-4 w-4 mr-2" />
      Создать план
    </Button>
  </div>

  <Card class="p-6">
    <div class="text-center py-12">
      <Calculator class="h-16 w-16 text-gray-400 mx-auto mb-4" />
      <h3 class="text-lg font-medium text-gray-900 mb-2">
        Страница в разработке
      </h3>
      <p class="text-gray-600">
        Компонент планирования бюджета будет портирован из React версии
      </p>
    </div>
  </Card>
</div>

// frontend/src/pages/Budget/index.tsx
import React from 'react';
import { Layout } from '../../components/common/Layout';
import { Card } from '../../components/common/Card';
import { Button } from '../../components/common/form/Button';

const BudgetPage: React.FC = () => {
  return (
    <Layout>
      <div className="space-y-6">
        <div className="flex justify-between items-center">
          <div>
            <h1 className="text-2xl font-semibold text-gray-900">Бюджет</h1>
            <p className="mt-1 text-sm text-gray-600">
              Планирование доходов и расходов
            </p>
          </div>
          <Button variant="primary">
            Создать бюджет
          </Button>
        </div>

        <Card>
          <p className="text-gray-500">Функционал будет реализован в следующих фазах</p>
        </Card>
      </div>
    </Layout>
  );
};

export default BudgetPage;
