// frontend-svelte/src/lib/components/reports/ChartSelector.svelte
<script lang="ts">
  import { 
    BarChart3, 
    PieChart, 
    TrendingUp, 
    Activity, 
    Gauge 
  } from 'lucide-svelte';
  import type { ReportFilters } from '$lib/services/reportService';

  // Props
  interface Props {
    currentType: 'composed' | 'pie' | 'trend' | 'waterfall' | 'gauge';
    onTypeChange: (type: 'composed' | 'pie' | 'trend' | 'waterfall' | 'gauge') => void;
    reportType: ReportFilters['report_type'];
  }
  
  let { currentType, onTypeChange, reportType }: Props = $props();

  // Chart type configurations with availability per report type
  const chartTypes = [
    {
      value: 'composed' as const,
      label: 'Комбинированный',
      icon: BarChart3,
      description: 'Столбцы и линии',
      availableFor: ['plan_fact', 'budget', 'analytics']
    },
    {
      value: 'pie' as const,
      label: 'Круговая диаграмма',
      icon: PieChart,
      description: 'Распределение по категориям',
      availableFor: ['budget', 'categories']
    },
    {
      value: 'trend' as const,
      label: 'Тренды',
      icon: TrendingUp,
      description: 'Временные ряды',
      availableFor: ['plan_fact', 'trends', 'analytics']
    },
    {
      value: 'waterfall' as const,
      label: 'Каскадная диаграмма',
      icon: Activity,
      description: 'Анализ отклонений',
      availableFor: ['plan_fact', 'analytics']
    },
    {
      value: 'gauge' as const,
      label: 'Индикатор',
      icon: Gauge,
      description: 'Выполнение бюджета',
      availableFor: ['budget', 'plan_fact']
    }
  ];

  // Filter chart types based on current report type
  $: availableChartTypes = chartTypes.filter(chart => 
    chart.availableFor.includes(reportType)
  );

  // Handle chart type selection
  function handleTypeSelect(type: typeof currentType) {
    if (type !== currentType) {
      onTypeChange(type);
    }
  }
</script>

<div class="space-y-3">
  <label class="text-xs font-medium text-gray-700 uppercase tracking-wide">
    Тип графика
  </label>
  
  <div class="grid grid-cols-1 gap-2">
    {#each availableChartTypes as chartType}
      <button
        on:click={() => handleTypeSelect(chartType.value)}
        class="flex items-center gap-3 p-3 rounded-lg border transition-all text-left {
          currentType === chartType.value
            ? 'bg-purple-50 border-purple-200 text-purple-900'
            : 'bg-white border-gray-200 text-gray-700 hover:border-gray-300 hover:bg-gray-50'
        }"
      >
        <div class="flex-shrink-0 {
          currentType === chartType.value
            ? 'text-purple-600'
            : 'text-gray-400'
        }">
          <svelte:component this={chartType.icon} class="h-4 w-4" />
        </div>
        
        <div class="flex-1 min-w-0">
          <div class="text-sm font-medium">
            {chartType.label}
          </div>
          <div class="text-xs text-gray-500 mt-1">
            {chartType.description}
          </div>
        </div>
        
        {#if currentType === chartType.value}
          <div class="flex-shrink-0">
            <div class="w-2 h-2 bg-purple-600 rounded-full"></div>
          </div>
        {/if}
      </button>
    {/each}
  </div>
  
  <!-- Info about selected chart type -->
  {#if currentType}
    {@const selectedChart = chartTypes.find(c => c.value === currentType)}
    {#if selectedChart}
      <div class="bg-purple-50 border border-purple-200 rounded-lg p-3 text-xs text-purple-800">
        <div class="flex items-center gap-2 mb-1">
          <svelte:component this={selectedChart.icon} class="h-3 w-3" />
          <span class="font-medium">Выбрано: {selectedChart.label}</span>
        </div>
        <p class="text-purple-600">{selectedChart.description}</p>
      </div>
    {/if}
  {/if}
</div>

// frontend/src/components/reports/ChartSelector.tsx
import React, { memo } from 'react';
import { 
  BarChart3, 
  PieChart, 
  TrendingUp, 
  BarChart2,
  Activity,
  LineChart
} from 'lucide-react';
import { 
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '../ui/select';

export type ChartType = 
  | 'plan_fact_bar' 
  | 'category_pie' 
  | 'budget_gauge' 
  | 'trend_line' 
  | 'variance_waterfall' 
  | 'composed';

export interface ChartTypeOption {
  value: ChartType;
  label: string;
  description: string;
  icon: React.ComponentType<{ className?: string }>;
  reportTypes: string[]; // Which report types support this chart
}

const chartTypeOptions: ChartTypeOption[] = [
  {
    value: 'plan_fact_bar',
    label: 'План vs Факт',
    description: 'Сравнение плановых и фактических показателей',
    icon: BarChart3,
    reportTypes: ['plan_fact', 'budget'],
  },
  {
    value: 'category_pie',
    label: 'Распределение по категориям',
    description: 'Круговая диаграмма распределения расходов',
    icon: PieChart,
    reportTypes: ['budget', 'plan_fact'],
  },
  {
    value: 'budget_gauge',
    label: 'Использование бюджета',
    description: 'Круговой индикатор освоения бюджета',
    icon: Activity,
    reportTypes: ['budget'],
  },
  {
    value: 'trend_line',
    label: 'Динамика по времени',
    description: 'Линейный график изменений во времени',
    icon: TrendingUp,
    reportTypes: ['plan_fact'],
  },
  {
    value: 'variance_waterfall',
    label: 'Анализ отклонений',
    description: 'Водопадная диаграмма отклонений',
    icon: BarChart2,
    reportTypes: ['plan_fact'],
  },
  {
    value: 'composed',
    label: 'Комбинированный график',
    description: 'Объединенные бары и линии',
    icon: LineChart,
    reportTypes: ['plan_fact', 'budget'],
  },
];

interface ChartSelectorProps {
  selectedType: ChartType;
  onTypeChange: (type: ChartType) => void;
  reportType: string;
  disabled?: boolean;
  className?: string;
}

export const ChartSelector: React.FC<ChartSelectorProps> = memo(({
  selectedType,
  onTypeChange,
  reportType,
  disabled = false,
  className = '',
}) => {
  // Filter options based on current report type
  const availableOptions = chartTypeOptions.filter(option =>
    option.reportTypes.includes(reportType)
  );

  // Ensure selected type is valid for current report type
  React.useEffect(() => {
    if (!availableOptions.find(option => option.value === selectedType)) {
      // If current selection is not available, select first available option
      if (availableOptions.length > 0) {
        onTypeChange(availableOptions[0].value);
      }
    }
  }, [reportType, selectedType, onTypeChange, availableOptions]);

  return (
    <div className={`space-y-2 ${className}`}>
      <label className="text-sm font-medium text-gray-700">
        Тип графика
      </label>
      <Select
        value={selectedType}
        onValueChange={onTypeChange}
        disabled={disabled}
      >
        <SelectTrigger className="w-full">
          <SelectValue placeholder="Выберите тип графика" />
        </SelectTrigger>
        <SelectContent>
          {availableOptions.map((option) => {
            const IconComponent = option.icon;
            return (
              <SelectItem key={option.value} value={option.value}>
                <div className="flex items-center gap-3 py-1">
                  <IconComponent className="h-4 w-4 text-gray-500" />
                  <div className="flex flex-col">
                    <span className="font-medium">{option.label}</span>
                    <span className="text-xs text-gray-500">
                      {option.description}
                    </span>
                  </div>
                </div>
              </SelectItem>
            );
          })}
        </SelectContent>
      </Select>
    </div>
  );
});

ChartSelector.displayName = 'ChartSelector';

// Export options for external use
export { chartTypeOptions };
export default ChartSelector;
