// frontend-svelte/src/lib/components/auth/AuthGuard.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { goto } from '$app/navigation';
  import { page } from '$app/stores';
  import { isAuthenticated, isAuthLoading, authStore } from '$lib/stores/auth.store';

  export let redirectTo = '/login';

  let mounted = false;

  onMount(async () => {
    mounted = true;
    // Check authentication status on mount
    if (!$isAuthenticated) {
      await authStore.checkAuth();
    }
  });

  // Reactive statement to handle authentication redirects
  $: {
    if (mounted && !$isAuthLoading && !$isAuthenticated) {
      // Save the attempted location and redirect to login
      const returnUrl = $page.url.pathname + $page.url.search;
      goto(`${redirectTo}?returnUrl=${encodeURIComponent(returnUrl)}`);
    }
  }
</script>

{#if $isAuthLoading}
  <div class="min-h-screen flex items-center justify-center">
    <div class="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600"></div>
  </div>
{:else if $isAuthenticated}
  <slot />
{/if}

// frontend/src/components/auth/AuthGuard.tsx
import React, { useEffect } from 'react';
import { Navigate, useLocation } from 'react-router-dom';
import { useAuthStore } from '../../stores/authStore';

interface AuthGuardProps {
  children: React.ReactNode;
}

export const AuthGuard: React.FC<AuthGuardProps> = ({ children }) => {
  const isAuthenticated = useAuthStore((state) => state.isAuthenticated);
  const isLoading = useAuthStore((state) => state.isLoading);
  const checkAuth = useAuthStore((state) => state.checkAuth);
  const location = useLocation();

  useEffect(() => {
    // Check authentication status on mount
    if (!isAuthenticated) {
      checkAuth();
    }
  }, [isAuthenticated, checkAuth]);

  if (isLoading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600"></div>
      </div>
    );
  }

  if (!isAuthenticated) {
    // Redirect to login page but save the attempted location
    return <Navigate to="/login" state={{ from: location }} replace />;
  }

  return <>{children}</>;
};
