// frontend-svelte/src/lib/components/reference/CostCenterManager.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  // TODO: Replace with SimpleDataTable when needed
  // import { createColumnHelper, type ColumnDef } from '@tanstack/svelte-table';
  import { currentUser } from '$lib/stores/auth.store';
  import { useToast } from '$lib/stores/toast.store';
  import { costCentersService, type CreateCostCenterData, type UpdateCostCenterData } from '$lib/services/costCenters.service';
  import type { CostCenter } from '$types';
  
  import CRUDTable from '$lib/components/common/CRUDTable.svelte';
  import Modal from '$lib/components/ui/Modal.svelte';
  import Button from '$lib/components/ui/Button.svelte';
  import Input from '$lib/components/ui/Input.svelte';
  import Badge from '$lib/components/ui/Badge.svelte';

  let costCenters: CostCenter[] = [];
  let loading = true;
  let showModal = false;
  let editingCostCenter: CostCenter | null = null;
  let isEditing = false;

  // Form state
  let formData = {
    cost_center_name: '',
    cost_center_order: 1,
    is_active: true
  };

  let formErrors: Record<string, string> = {};

  const toast = useToast();

  // Define table columns for CRUDTable
  const columns = [
    {
      key: 'cost_center_name',
      header: 'Название МВЗ',
      sortable: true
    },
    {
      key: 'cost_center_order',
      header: 'Порядок',
      sortable: true
    },
    {
      key: 'is_active',
      header: 'Статус',
      render: (item: CostCenter) => item.is_active ? 'Активен' : 'Неактивен'
    },
    {
      key: 'created_at',
      header: 'Дата создания',
      sortable: true,
      render: (item: CostCenter) => {
        if (!item.created_at) return '-';
        return new Date(item.created_at).toLocaleDateString('ru-RU', {
          day: '2-digit',
          month: '2-digit',
          year: 'numeric',
          hour: '2-digit',
          minute: '2-digit',
        });
      }
    }
  ];

  // Load cost centers
  async function fetchCostCenters() {
    if (!$currentUser?.user_id) return;
    
    try {
      loading = true;
      costCenters = await costCentersService.getByUserId($currentUser.user_id);
    } catch (error: any) {
      toast.error('Ошибка', 'Не удалось загрузить места возникновения затрат');
      console.error('Error fetching cost centers:', error);
    } finally {
      loading = false;
    }
  }

  onMount(() => {
    fetchCostCenters();
  });

  // Form validation
  function validateForm(): boolean {
    formErrors = {};

    if (!formData.cost_center_name || formData.cost_center_name.trim().length < 3) {
      formErrors.cost_center_name = 'Название должно содержать минимум 3 символа';
    }

    if (formData.cost_center_name && formData.cost_center_name.trim().length > 100) {
      formErrors.cost_center_name = 'Название не должно превышать 100 символов';
    }

    if (formData.cost_center_order < 1) {
      formErrors.cost_center_order = 'Порядок должен быть больше 0';
    }

    return Object.keys(formErrors).length === 0;
  }

  // Handle add
  function handleAdd() {
    isEditing = false;
    editingCostCenter = null;
    formData = {
      cost_center_name: '',
      cost_center_order: Math.max(...costCenters.map(cc => cc.cost_center_order), 0) + 1,
      is_active: true
    };
    formErrors = {};
    showModal = true;
  }

  // Handle edit
  function handleEdit(event: CustomEvent) {
    const { item } = event.detail;
    isEditing = true;
    editingCostCenter = item;
    formData = {
      cost_center_name: item.cost_center_name,
      cost_center_order: item.cost_center_order,
      is_active: item.is_active ?? true
    };
    formErrors = {};
    showModal = true;
  }

  // Handle delete
  async function handleDelete(event: CustomEvent) {
    const { id } = event.detail;
    
    try {
      await costCentersService.delete(id);
      await fetchCostCenters();
      toast.success('Успешно', 'Место возникновения затрат удалено');
    } catch (error: any) {
      toast.error('Ошибка', error.message || 'Не удалось удалить место возникновения затрат');
    }
  }

  // Handle bulk delete
  async function handleBulkDelete(event: CustomEvent) {
    const { ids } = event.detail;
    
    try {
      await costCentersService.bulkDelete(ids);
      await fetchCostCenters();
      toast.success('Успешно', `Удалено мест возникновения затрат: ${ids.length}`);
    } catch (error: any) {
      toast.error('Ошибка', error.message || 'Не удалось удалить места возникновения затрат');
    }
  }

  // Handle form submit
  async function handleSubmit() {
    if (!validateForm()) {
      return;
    }

    if (!$currentUser?.user_id) {
      toast.error('Ошибка', 'Пользователь не авторизован');
      return;
    }

    try {
      if (isEditing && editingCostCenter) {
        const updateData: UpdateCostCenterData = { ...formData };
        await costCentersService.update(editingCostCenter.cost_center_id, updateData);
        toast.success('Успешно', 'Место возникновения затрат обновлено');
      } else {
        const createData: CreateCostCenterData = {
          ...formData,
          user_id: $currentUser.user_id
        };
        await costCentersService.create(createData);
        toast.success('Успешно', 'Место возникновения затрат создано');
      }
      
      await fetchCostCenters();
      showModal = false;
    } catch (error: any) {
      toast.error('Ошибка', error.message || 'Не удалось сохранить место возникновения затрат');
    }
  }

  // Handle export
  async function handleExport() {
    try {
      const csvContent = await costCentersService.exportToCsv(costCenters);
      const blob = new Blob(['\ufeff' + csvContent], { type: 'text/csv;charset=utf-8;' });
      const link = document.createElement('a');
      link.href = URL.createObjectURL(blob);
      link.download = `cost_centers_${new Date().toISOString().split('T')[0]}.csv`;
      link.click();
      toast.success('Успешно', 'Данные экспортированы');
    } catch (error: any) {
      toast.error('Ошибка', 'Не удалось экспортировать данные');
    }
  }

  // Handle import
  async function handleImport(event: CustomEvent) {
    const { file } = event.detail;
    
    if (!$currentUser?.user_id) {
      toast.error('Ошибка', 'Пользователь не авторизован');
      return;
    }

    try {
      const text = await file.text();
      const importData = await costCentersService.importFromCsv(text, $currentUser.user_id);
      
      // Import each cost center
      for (const ccData of importData) {
        await costCentersService.create(ccData);
      }
      
      await fetchCostCenters();
      toast.success('Успешно', `Импортировано мест возникновения затрат: ${importData.length}`);
    } catch (error: any) {
      toast.error('Ошибка', error.message || 'Не удалось импортировать данные');
    }
  }

  function handleCloseModal() {
    showModal = false;
    formErrors = {};
  }
</script>

<CRUDTable
  title="Места возникновения затрат (МВЗ)"
  data={costCenters}
  {columns}
  {loading}
  searchable={true}
  exportable={true}
  importable={true}
  addButtonText="Добавить МВЗ"
  emptyMessage="Нет добавленных мест возникновения затрат. Нажмите 'Добавить МВЗ' для создания нового."
  on:add={handleAdd}
  on:edit={handleEdit}
  on:delete={handleDelete}
  on:bulkDelete={handleBulkDelete}
  on:export={handleExport}
  on:import={handleImport}
/>

<Modal 
  bind:open={showModal}
  title={isEditing ? 'Редактировать МВЗ' : 'Добавить МВЗ'}
  on:close={handleCloseModal}
>
  <form on:submit|preventDefault={handleSubmit} class="space-y-4">
    <div>
      <label for="cost_center_name" class="block text-sm font-medium text-gray-700 mb-1">
        Название МВЗ *
      </label>
      <Input
        id="cost_center_name"
        bind:value={formData.cost_center_name}
        placeholder="Введите название места возникновения затрат"
        maxlength="100"
        class={formErrors.cost_center_name ? 'border-red-500' : ''}
      />
      {#if formErrors.cost_center_name}
        <p class="text-red-500 text-xs mt-1">{formErrors.cost_center_name}</p>
      {/if}
    </div>

    <div>
      <label for="cost_center_order" class="block text-sm font-medium text-gray-700 mb-1">
        Порядок *
      </label>
      <Input
        id="cost_center_order"
        type="number"
        min="1"
        bind:value={formData.cost_center_order}
        class={formErrors.cost_center_order ? 'border-red-500' : ''}
      />
      {#if formErrors.cost_center_order}
        <p class="text-red-500 text-xs mt-1">{formErrors.cost_center_order}</p>
      {/if}
    </div>

    <div class="flex items-center">
      <input
        id="is_active"
        type="checkbox"
        bind:checked={formData.is_active}
        class="h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-300 rounded"
      />
      <label for="is_active" class="ml-2 block text-sm text-gray-900">
        Активен
      </label>
    </div>
  </form>

  <svelte:fragment slot="footer">
    <Button variant="outline" on:click={handleCloseModal}>
      Отмена
    </Button>
    <Button type="submit" on:click={handleSubmit}>
      {isEditing ? 'Обновить' : 'Создать'}
    </Button>
  </svelte:fragment>
</Modal>

// frontend/src/components/reference/CostCenterManager.tsx
import React, { useState, useEffect } from 'react';
import { CRUDTable, CRUDField } from './CRUDTable';
import { Badge } from '../ui/badge';
import { toast } from '../ui/use-toast';
import { useAuthStore } from '../../stores/authStore';
import { apiClient } from '../../api/client';

interface CostCenter {
  id: number;
  cost_center_id: number;
  cost_center_name: string;
  cost_center_order: number;
  user_id: number;
  is_active?: boolean;
  created_at?: string;
  updated_at?: string;
}

export const CostCenterManager: React.FC = () => {
  const [costCenters, setCostCenters] = useState<CostCenter[]>([]);
  const [loading, setLoading] = useState(true);
  const { user } = useAuthStore();

  // Define fields for CRUD table
  const fields: CRUDField<CostCenter>[] = [
    {
      key: 'cost_center_name',
      label: 'Название МВЗ',
      type: 'text',
      required: true,
      width: 'w-96',
      validation: (value) => {
        if (!value || value.trim().length < 3) {
          return 'Название должно содержать минимум 3 символа';
        }
        if (value.trim().length > 100) {
          return 'Название не должно превышать 100 символов';
        }
        return null;
      },
    },
    {
      key: 'cost_center_order',
      label: 'Порядок',
      type: 'number',
      required: true,
      width: 'w-24',
      validation: (value) => {
        if (Number(value) < 1) {
          return 'Порядок должен быть больше 0';
        }
        return null;
      },
    },
    {
      key: 'is_active',
      label: 'Статус',
      type: 'boolean',
      width: 'w-32',
      renderCell: (value) => value ? (
        <Badge variant="default">Активен</Badge>
      ) : (
        <Badge variant="secondary">Неактивен</Badge>
      ),
    },
    {
      key: 'created_at',
      label: 'Дата создания',
      type: 'date',
      width: 'w-40',
      sortable: true,
      filterable: false,
      renderCell: (value) => {
        if (!value) return '-';
        return new Date(value).toLocaleDateString('ru-RU', {
          day: '2-digit',
          month: '2-digit',
          year: 'numeric',
          hour: '2-digit',
          minute: '2-digit',
        });
      },
      renderEdit: () => null, // Read-only in edit mode
    },
  ];

  // Fetch cost centers
  const fetchCostCenters = async () => {
    if (!user?.user_id) return;
    
    try {
      setLoading(true);
      const response = await apiClient.get(`/cost_centers?user_id=${user.user_id}`);
      setCostCenters(response.data.map((cc: any) => ({
        ...cc,
        id: cc.cost_center_id, // Map cost_center_id to id for CRUD table
      })));
    } catch (error) {
      toast({
        title: 'Ошибка',
        description: 'Не удалось загрузить центры затрат',
        variant: 'destructive',
      });
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchCostCenters();
  }, [user]);

  // Add cost center
  const handleAdd = async (data: Omit<CostCenter, 'id'>) => {
    if (!user?.user_id) return;
    
    const newCostCenter = {
      ...data,
      user_id: user.user_id,
      is_active: data.is_active !== false, // Default to true if not specified
    };

    try {
      await apiClient.post('/cost_centers', newCostCenter);
      await fetchCostCenters();
    } catch (error: any) {
      throw new Error(error.response?.data?.detail || 'Не удалось добавить центр затрат');
    }
  };

  // Update cost center
  const handleUpdate = async (id: number, data: Partial<CostCenter>) => {
    try {
      await apiClient.put(`/cost_centers/${id}`, data);
      await fetchCostCenters();
    } catch (error: any) {
      throw new Error(error.response?.data?.detail || 'Не удалось обновить центр затрат');
    }
  };

  // Delete cost center
  const handleDelete = async (id: number) => {
    try {
      await apiClient.delete(`/cost_centers/${id}`);
      await fetchCostCenters();
    } catch (error: any) {
      throw new Error(error.response?.data?.detail || 'Не удалось удалить центр затрат');
    }
  };

  // Bulk delete cost centers
  const handleBulkDelete = async (ids: number[]) => {
    try {
      // API doesn't support bulk delete, so we'll delete one by one
      await Promise.all(ids.map(id => apiClient.delete(`/cost_centers/${id}`)));
      await fetchCostCenters();
    } catch (error: any) {
      throw new Error(error.response?.data?.detail || 'Не удалось удалить центры затрат');
    }
  };

  // Export cost centers
  const handleExport = () => {
    const csvContent = [
      ['ID', 'Название МВЗ', 'Порядок', 'Статус', 'Дата создания'].join(','),
      ...costCenters.map(cc => [
        cc.cost_center_id,
        `"${cc.cost_center_name}"`,
        cc.cost_center_order,
        cc.is_active ? 'Активен' : 'Неактивен',
        cc.created_at ? new Date(cc.created_at).toLocaleDateString('ru-RU') : '',
      ].join(','))
    ].join('\n');

    const blob = new Blob(['\ufeff' + csvContent], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.download = `cost_centers_${new Date().toISOString().split('T')[0]}.csv`;
    link.click();
  };

  // Import cost centers
  const handleImport = async (file: File) => {
    const text = await file.text();
    const lines = text.split('\n').slice(1); // Skip header
    
    const newCostCenters: Omit<CostCenter, 'id'>[] = [];
    
    for (const line of lines) {
      if (!line.trim()) continue;
      
      const [, name, order, status] = line.split(',').map(v => v.replace(/"/g, '').trim());
      
      newCostCenters.push({
        cost_center_name: name,
        cost_center_order: Number(order),
        is_active: status === 'Активен',
        user_id: user!.user_id,
      } as Omit<CostCenter, 'id'>);
    }

    // Add cost centers one by one
    for (const cc of newCostCenters) {
      await handleAdd(cc);
    }
  };

  return (
    <CRUDTable
      title="Места возникновения затрат (МВЗ)"
      data={costCenters}
      fields={fields}
      onAdd={handleAdd}
      onUpdate={handleUpdate}
      onDelete={handleDelete}
      onBulkDelete={handleBulkDelete}
      loading={loading}
      searchable={true}
      exportable={true}
      importable={true}
      onExport={handleExport}
      onImport={handleImport}
      emptyMessage="Нет добавленных центров затрат. Нажмите 'Добавить МВЗ' для создания нового."
      addButtonText="Добавить МВЗ"
    />
  );
};
