// frontend-svelte/src/lib/components/common/CRUDTable.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  import { writable } from 'svelte/store';
  import { 
    createSvelteTable, 
    flexRender,
    getCoreRowModel,
    getSortedRowModel,
    getFilteredRowModel,
    getPaginationRowModel,
    type ColumnDef
  } from '@tanstack/svelte-table';
  import { 
    Plus, 
    Edit, 
    Trash2, 
    Download, 
    Upload, 
    MoreHorizontal,
    ChevronUp, 
    ChevronDown, 
    ChevronsUpDown
  } from 'lucide-svelte';
  import { clsx } from 'clsx';
  import Button from '$lib/components/ui/Button.svelte';
  import Input from '$lib/components/ui/Input.svelte';
  import Card from '$lib/components/ui/Card.svelte';
  import Badge from '$lib/components/ui/Badge.svelte';
  import Table from '$lib/components/ui/Table.svelte';
  import TableBody from '$lib/components/ui/TableBody.svelte';
  import TableCell from '$lib/components/ui/TableCell.svelte';
  import TableHead from '$lib/components/ui/TableHead.svelte';
  import TableHeader from '$lib/components/ui/TableHeader.svelte';
  import TableRow from '$lib/components/ui/TableRow.svelte';
  import Loading from './Loading.svelte';
  import { useToast } from '$lib/stores/toast.store';

  type T = $$Generic;

  export let title: string;
  export let data: T[];
  export let columns: ColumnDef<T>[];
  export let loading = false;
  export let searchable = true;
  export let exportable = false;
  export let importable = false;
  export let addButtonText = 'Добавить';
  export let emptyMessage = 'Нет данных для отображения';
  export let searchPlaceholder = 'Поиск...';
  export let pageSize = 10;

  const dispatch = createEventDispatcher<{
    add: void;
    edit: { id: string | number; item: T };
    delete: { id: string | number; item: T };
    bulkDelete: { ids: (string | number)[]; items: T[] };
    export: void;
    import: { file: File };
  }>();

  const toast = useToast();
  const sorting = writable([]);
  const columnFilters = writable([]);
  const globalFilter = writable('');
  const rowSelection = writable({});

  let fileInput: HTMLInputElement;

  // Add selection column and actions column to the provided columns
  $: enhancedColumns = [
    {
      id: 'select',
      header: ({ table }) => {
        return {
          component: 'input',
          props: {
            type: 'checkbox',
            checked: table.getIsAllPageRowsSelected(),
            indeterminate: table.getIsSomePageRowsSelected(),
            onChange: (e: Event) => table.toggleAllPageRowsSelected((e.target as HTMLInputElement).checked)
          }
        };
      },
      cell: ({ row }) => {
        return {
          component: 'input',
          props: {
            type: 'checkbox',
            checked: row.getIsSelected(),
            disabled: !row.getCanSelect(),
            onChange: (e: Event) => row.toggleSelected((e.target as HTMLInputElement).checked)
          }
        };
      },
      enableSorting: false,
      enableHiding: false,
    },
    ...columns,
    {
      id: 'actions',
      header: 'Действия',
      cell: ({ row }) => {
        const item = row.original;
        return {
          component: 'actions',
          props: { item }
        };
      },
      enableSorting: false,
    }
  ] as ColumnDef<T>[];

  $: options = {
    data,
    columns: enhancedColumns,
    state: {
      sorting: $sorting,
      columnFilters: $columnFilters,
      globalFilter: $globalFilter,
      rowSelection: $rowSelection,
    },
    onSortingChange: (updater: any) => sorting.update(updater),
    onColumnFiltersChange: (updater: any) => columnFilters.update(updater),
    onGlobalFilterChange: (updater: any) => globalFilter.update(updater),
    onRowSelectionChange: (updater: any) => rowSelection.update(updater),
    getCoreRowModel: getCoreRowModel(),
    getSortedRowModel: getSortedRowModel(),
    getFilteredRowModel: getFilteredRowModel(),
    getPaginationRowModel: getPaginationRowModel(),
    enableRowSelection: true,
    initialState: {
      pagination: {
        pageSize,
      },
    },
  };

  const table = createSvelteTable(options);

  function handleAdd() {
    dispatch('add');
  }

  function handleEdit(item: T) {
    const id = (item as any).id || (item as any).period_id || (item as any).financial_center_id || (item as any).cost_center_id || (item as any).nomenclature_id;
    dispatch('edit', { id, item });
  }

  function handleDelete(item: T) {
    const id = (item as any).id || (item as any).period_id || (item as any).financial_center_id || (item as any).cost_center_id || (item as any).nomenclature_id;
    if (confirm('Вы уверены, что хотите удалить эту запись?')) {
      dispatch('delete', { id, item });
    }
  }

  function handleBulkDelete() {
    const selectedRows = $table.getFilteredSelectedRowModel().rows;
    if (selectedRows.length === 0) {
      toast.error('Ошибка', 'Выберите записи для удаления');
      return;
    }

    if (confirm(`Вы уверены, что хотите удалить ${selectedRows.length} записей?`)) {
      const ids = selectedRows.map(row => {
        const item = row.original;
        return (item as any).id || (item as any).period_id || (item as any).financial_center_id || (item as any).cost_center_id || (item as any).nomenclature_id;
      });
      const items = selectedRows.map(row => row.original);
      dispatch('bulkDelete', { ids, items });
      
      // Clear selection after bulk delete
      rowSelection.set({});
    }
  }

  function handleExport() {
    dispatch('export');
  }

  function handleImport() {
    fileInput.click();
  }

  function handleFileSelected(event: Event) {
    const file = (event.target as HTMLInputElement).files?.[0];
    if (file) {
      dispatch('import', { file });
      // Clear file input
      if (fileInput) {
        fileInput.value = '';
      }
    }
  }

  $: selectedRowsCount = Object.keys($rowSelection).length;
</script>

<Card class="p-6">
  <div class="space-y-4">
    <!-- Header -->
    <div class="flex justify-between items-center">
      <h2 class="text-2xl font-bold">{title}</h2>
      <div class="flex gap-2">
        {#if selectedRowsCount > 0}
          <Button variant="destructive" size="sm" on:click={handleBulkDelete}>
            <Trash2 class="h-4 w-4 mr-2" />
            Удалить ({selectedRowsCount})
          </Button>
        {/if}
        
        {#if exportable}
          <Button variant="outline" size="sm" on:click={handleExport}>
            <Download class="h-4 w-4 mr-2" />
            Экспорт
          </Button>
        {/if}
        
        {#if importable}
          <Button variant="outline" size="sm" on:click={handleImport}>
            <Upload class="h-4 w-4 mr-2" />
            Импорт
          </Button>
          <input
            bind:this={fileInput}
            type="file"
            accept=".csv"
            class="hidden"
            on:change={handleFileSelected}
          />
        {/if}
        
        <Button on:click={handleAdd}>
          <Plus class="h-4 w-4 mr-2" />
          {addButtonText}
        </Button>
      </div>
    </div>

    <!-- Search -->
    {#if searchable}
      <div class="max-w-sm">
        <Input
          placeholder={searchPlaceholder}
          bind:value={$globalFilter}
        />
      </div>
    {/if}

    <!-- Table -->
    {#if loading}
      <div class="flex justify-center items-center py-8">
        <Loading text="Загрузка данных..." />
      </div>
    {:else}
      <div class="rounded-md border">
        <Table>
          <TableHeader>
            {#each $table.getHeaderGroups() as headerGroup (headerGroup.id)}
              <TableRow>
                {#each headerGroup.headers as header (header.id)}
                  <TableHead>
                    {#if !header.isPlaceholder}
                      {#if header.id === 'select'}
                        <input
                          type="checkbox"
                          checked={$table.getIsAllPageRowsSelected()}
                          on:change={(e) => $table.toggleAllPageRowsSelected(e.target.checked)}
                        />
                      {:else if header.column.getCanSort()}
                        <div
                          class="cursor-pointer select-none flex items-center gap-1"
                          on:click={header.column.getToggleSortingHandler()}
                          on:keydown={(e) => e.key === 'Enter' && header.column.getToggleSortingHandler()?.(e)}
                          role="button"
                          tabindex="0"
                        >
                          <svelte:component 
                            this={flexRender(header.column.columnDef.header, header.getContext())}
                          />
                          {#if header.column.getIsSorted() === 'asc'}
                            <ChevronUp class="h-4 w-4" />
                          {:else if header.column.getIsSorted() === 'desc'}
                            <ChevronDown class="h-4 w-4" />
                          {:else}
                            <ChevronsUpDown class="h-4 w-4 opacity-50" />
                          {/if}
                        </div>
                      {:else}
                        <svelte:component 
                          this={flexRender(header.column.columnDef.header, header.getContext())}
                        />
                      {/if}
                    {/if}
                  </TableHead>
                {/each}
              </TableRow>
            {/each}
          </TableHeader>
          <TableBody>
            {#if $table.getRowModel().rows.length > 0}
              {#each $table.getRowModel().rows as row (row.id)}
                <TableRow class:selected={row.getIsSelected()}>
                  {#each row.getVisibleCells() as cell (cell.id)}
                    <TableCell>
                      {#if cell.column.id === 'select'}
                        <input
                          type="checkbox"
                          checked={row.getIsSelected()}
                          disabled={!row.getCanSelect()}
                          on:change={(e) => row.toggleSelected(e.target.checked)}
                        />
                      {:else if cell.column.id === 'actions'}
                        <div class="flex gap-1">
                          <Button 
                            variant="ghost" 
                            size="sm" 
                            on:click={() => handleEdit(row.original)}
                          >
                            <Edit class="h-4 w-4" />
                          </Button>
                          <Button 
                            variant="ghost" 
                            size="sm" 
                            on:click={() => handleDelete(row.original)}
                          >
                            <Trash2 class="h-4 w-4" />
                          </Button>
                        </div>
                      {:else}
                        <svelte:component 
                          this={flexRender(cell.column.columnDef.cell, cell.getContext())}
                        />
                      {/if}
                    </TableCell>
                  {/each}
                </TableRow>
              {/each}
            {:else}
              <TableRow>
                <TableCell colSpan={enhancedColumns.length} class="h-24 text-center">
                  {emptyMessage}
                </TableCell>
              </TableRow>
            {/if}
          </TableBody>
        </Table>
      </div>
    {/if}

    <!-- Pagination -->
    {#if !loading && $table.getPageCount() > 1}
      <div class="flex items-center justify-between">
        <div class="text-sm text-gray-600">
          Показано {$table.getState().pagination.pageIndex * pageSize + 1} -{' '}
          {Math.min(
            ($table.getState().pagination.pageIndex + 1) * pageSize,
            data.length
          )}{' '}
          из {data.length}
        </div>
        <div class="flex gap-2">
          <Button
            variant="outline"
            size="sm"
            on:click={() => $table.previousPage()}
            disabled={!$table.getCanPreviousPage()}
          >
            Назад
          </Button>
          <Button
            variant="outline"
            size="sm"
            on:click={() => $table.nextPage()}
            disabled={!$table.getCanNextPage()}
          >
            Вперед
          </Button>
        </div>
      </div>
    {/if}
  </div>
</Card>

<style>
  .selected {
    @apply bg-blue-50;
  }
</style>

// frontend/src/components/reference/CRUDTable.tsx
import React, { useState, useEffect, useCallback } from 'react';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '../ui/table';
import { Button } from '../ui/button';
import { Input } from '../ui/input';
import { Card, CardContent, CardHeader, CardTitle } from '../ui/card';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '../ui/alert-dialog';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '../ui/dialog';
import { Badge } from '../ui/badge';
import { Checkbox } from '../ui/checkbox';
import { toast } from '../ui/use-toast';
import {
  Plus,
  Edit2,
  Trash2,
  Save,
  X,
  Search,
  Filter,
  Download,
  Upload,
  CheckSquare,
  Square,
  MoreVertical,
} from 'lucide-react';
import { clsx } from 'clsx';

// Generic types for CRUD operations
export type CRUDField<T = any> = {
  key: keyof T;
  label: string;
  type: 'text' | 'number' | 'date' | 'boolean' | 'select' | 'custom';
  required?: boolean;
  options?: { value: string; label: string }[];
  renderCell?: (value: any, item: T) => React.ReactNode;
  renderEdit?: (value: any, onChange: (value: any) => void, item: T) => React.ReactNode;
  validation?: (value: any) => string | null;
  width?: string;
  sortable?: boolean;
  filterable?: boolean;
};

export interface CRUDTableProps<T extends { id: number | string }> {
  title: string;
  data: T[];
  fields: CRUDField<T>[];
  onAdd: (item: Omit<T, 'id'>) => Promise<void>;
  onUpdate: (id: T['id'], item: Partial<T>) => Promise<void>;
  onDelete: (id: T['id']) => Promise<void>;
  onBulkDelete?: (ids: T['id'][]) => Promise<void>;
  loading?: boolean;
  searchable?: boolean;
  exportable?: boolean;
  importable?: boolean;
  onExport?: () => void;
  onImport?: (file: File) => Promise<void>;
  emptyMessage?: string;
  addButtonText?: string;
  customActions?: (item: T) => React.ReactNode;
}

export function CRUDTable<T extends { id: number | string }>({
  title,
  data,
  fields,
  onAdd,
  onUpdate,
  onDelete,
  onBulkDelete,
  loading = false,
  searchable = true,
  exportable = false,
  importable = false,
  onExport,
  onImport,
  emptyMessage = 'Нет данных',
  addButtonText = 'Добавить',
  customActions,
}: CRUDTableProps<T>) {
  const [searchQuery, setSearchQuery] = useState('');
  const [editingId, setEditingId] = useState<T['id'] | null>(null);
  const [editingData, setEditingData] = useState<Partial<T>>({});
  const [isAddDialogOpen, setIsAddDialogOpen] = useState(false);
  const [newItemData, setNewItemData] = useState<Partial<T>>({});
  const [deleteConfirmId, setDeleteConfirmId] = useState<T['id'] | null>(null);
  const [selectedIds, setSelectedIds] = useState<T['id'][]>([]);
  const [bulkDeleteConfirm, setBulkDeleteConfirm] = useState(false);
  const [sortField, setSortField] = useState<keyof T | null>(null);
  const [sortDirection, setSortDirection] = useState<'asc' | 'desc'>('asc');

  // Filter data based on search query
  const filteredData = data.filter((item) => {
    if (!searchQuery) return true;
    
    return fields.some((field) => {
      if (!field.filterable !== false) {
        const value = item[field.key];
        if (value === null || value === undefined) return false;
        return String(value).toLowerCase().includes(searchQuery.toLowerCase());
      }
      return false;
    });
  });

  // Sort data
  const sortedData = [...filteredData].sort((a, b) => {
    if (!sortField) return 0;
    
    const aValue = a[sortField];
    const bValue = b[sortField];
    
    if (aValue === null || aValue === undefined) return 1;
    if (bValue === null || bValue === undefined) return -1;
    
    if (aValue < bValue) return sortDirection === 'asc' ? -1 : 1;
    if (aValue > bValue) return sortDirection === 'asc' ? 1 : -1;
    return 0;
  });

  // Handle sorting
  const handleSort = (field: keyof T) => {
    if (sortField === field) {
      setSortDirection(sortDirection === 'asc' ? 'desc' : 'asc');
    } else {
      setSortField(field);
      setSortDirection('asc');
    }
  };

  // Start editing
  const startEditing = (item: T) => {
    setEditingId(item.id);
    setEditingData({ ...item });
  };

  // Cancel editing
  const cancelEditing = () => {
    setEditingId(null);
    setEditingData({});
  };

  // Save editing
  const saveEditing = async () => {
    if (!editingId) return;

    // Validate fields
    for (const field of fields) {
      if (field.required && !editingData[field.key]) {
        toast({
          title: 'Ошибка валидации',
          description: `Поле "${field.label}" обязательно для заполнения`,
          variant: 'destructive',
        });
        return;
      }

      if (field.validation) {
        const error = field.validation(editingData[field.key]);
        if (error) {
          toast({
            title: 'Ошибка валидации',
            description: error,
            variant: 'destructive',
          });
          return;
        }
      }
    }

    try {
      await onUpdate(editingId, editingData);
      setEditingId(null);
      setEditingData({});
      toast({
        title: 'Успешно',
        description: 'Запись обновлена',
      });
    } catch (error) {
      toast({
        title: 'Ошибка',
        description: 'Не удалось обновить запись',
        variant: 'destructive',
      });
    }
  };

  // Handle add new item
  const handleAdd = async () => {
    // Validate fields
    for (const field of fields) {
      if (field.required && !newItemData[field.key]) {
        toast({
          title: 'Ошибка валидации',
          description: `Поле "${field.label}" обязательно для заполнения`,
          variant: 'destructive',
        });
        return;
      }

      if (field.validation) {
        const error = field.validation(newItemData[field.key]);
        if (error) {
          toast({
            title: 'Ошибка валидации',
            description: error,
            variant: 'destructive',
          });
          return;
        }
      }
    }

    try {
      await onAdd(newItemData as Omit<T, 'id'>);
      setIsAddDialogOpen(false);
      setNewItemData({});
      toast({
        title: 'Успешно',
        description: 'Запись добавлена',
      });
    } catch (error) {
      toast({
        title: 'Ошибка',
        description: 'Не удалось добавить запись',
        variant: 'destructive',
      });
    }
  };

  // Handle delete
  const handleDelete = async () => {
    if (!deleteConfirmId) return;

    try {
      await onDelete(deleteConfirmId);
      setDeleteConfirmId(null);
      toast({
        title: 'Успешно',
        description: 'Запись удалена',
      });
    } catch (error) {
      toast({
        title: 'Ошибка',
        description: 'Не удалось удалить запись',
        variant: 'destructive',
      });
    }
  };

  // Handle bulk delete
  const handleBulkDelete = async () => {
    if (!onBulkDelete || selectedIds.length === 0) return;

    try {
      await onBulkDelete(selectedIds);
      setSelectedIds([]);
      setBulkDeleteConfirm(false);
      toast({
        title: 'Успешно',
        description: `Удалено записей: ${selectedIds.length}`,
      });
    } catch (error) {
      toast({
        title: 'Ошибка',
        description: 'Не удалось удалить записи',
        variant: 'destructive',
      });
    }
  };

  // Toggle selection
  const toggleSelection = (id: T['id']) => {
    setSelectedIds(prev =>
      prev.includes(id)
        ? prev.filter(i => i !== id)
        : [...prev, id]
    );
  };

  // Toggle all selection
  const toggleAllSelection = () => {
    if (selectedIds.length === sortedData.length) {
      setSelectedIds([]);
    } else {
      setSelectedIds(sortedData.map(item => item.id));
    }
  };

  // Handle file import
  const handleFileImport = async (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (file && onImport) {
      try {
        await onImport(file);
        toast({
          title: 'Успешно',
          description: 'Данные импортированы',
        });
      } catch (error) {
        toast({
          title: 'Ошибка',
          description: 'Не удалось импортировать данные',
          variant: 'destructive',
        });
      }
    }
  };

  // Render cell value
  const renderCellValue = (field: CRUDField<T>, item: T) => {
    const value = item[field.key];

    if (editingId === item.id) {
      if (field.renderEdit) {
        return field.renderEdit(
          editingData[field.key],
          (newValue) => setEditingData({ ...editingData, [field.key]: newValue }),
          item
        );
      }

      switch (field.type) {
        case 'text':
        case 'number':
        case 'date':
          return (
            <Input
              type={field.type}
              value={editingData[field.key] || ''}
              onChange={(e) => setEditingData({
                ...editingData,
                [field.key]: field.type === 'number' ? Number(e.target.value) : e.target.value
              })}
              className="h-8"
            />
          );
        case 'boolean':
          return (
            <Checkbox
              checked={editingData[field.key] || false}
              onCheckedChange={(checked) => setEditingData({
                ...editingData,
                [field.key]: checked
              })}
            />
          );
        case 'select':
          return (
            <select
              value={editingData[field.key] || ''}
              onChange={(e) => setEditingData({
                ...editingData,
                [field.key]: e.target.value
              })}
              className="h-8 w-full rounded border px-2"
            >
              <option value="">Выберите...</option>
              {field.options?.map(option => (
                <option key={option.value} value={option.value}>
                  {option.label}
                </option>
              ))}
            </select>
          );
        default:
          return value;
      }
    }

    if (field.renderCell) {
      return field.renderCell(value, item);
    }

    switch (field.type) {
      case 'boolean':
        return value ? (
          <Badge variant="default">Да</Badge>
        ) : (
          <Badge variant="secondary">Нет</Badge>
        );
      case 'date':
        return value ? new Date(value as any).toLocaleDateString('ru-RU') : '-';
      default:
        return value || '-';
    }
  };

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center justify-between">
          <CardTitle>{title}</CardTitle>
          <div className="flex items-center gap-2">
            {searchable && (
              <div className="relative">
                <Search className="absolute left-2 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-400" />
                <Input
                  placeholder="Поиск..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className="h-9 w-64 pl-8"
                />
              </div>
            )}
            {selectedIds.length > 0 && onBulkDelete && (
              <Button
                variant="destructive"
                size="sm"
                onClick={() => setBulkDeleteConfirm(true)}
              >
                <Trash2 className="h-4 w-4 mr-1" />
                Удалить ({selectedIds.length})
              </Button>
            )}
            {importable && (
              <label>
                <Button variant="outline" size="sm" asChild>
                  <span>
                    <Upload className="h-4 w-4 mr-1" />
                    Импорт
                  </span>
                </Button>
                <input
                  type="file"
                  hidden
                  accept=".csv,.xlsx,.xls"
                  onChange={handleFileImport}
                />
              </label>
            )}
            {exportable && (
              <Button variant="outline" size="sm" onClick={onExport}>
                <Download className="h-4 w-4 mr-1" />
                Экспорт
              </Button>
            )}
            <Button size="sm" onClick={() => setIsAddDialogOpen(true)}>
              <Plus className="h-4 w-4 mr-1" />
              {addButtonText}
            </Button>
          </div>
        </div>
      </CardHeader>
      <CardContent>
        {loading ? (
          <div className="flex items-center justify-center py-8">
            <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
          </div>
        ) : sortedData.length === 0 ? (
          <div className="text-center py-8 text-gray-500">
            {emptyMessage}
          </div>
        ) : (
          <div className="rounded-md border">
            <Table>
              <TableHeader>
                <TableRow>
                  {onBulkDelete && (
                    <TableHead className="w-12">
                      <Checkbox
                        checked={selectedIds.length === sortedData.length && sortedData.length > 0}
                        onCheckedChange={toggleAllSelection}
                      />
                    </TableHead>
                  )}
                  {fields.map((field) => (
                    <TableHead
                      key={String(field.key)}
                      className={clsx(
                        field.width,
                        field.sortable !== false && 'cursor-pointer hover:bg-gray-50'
                      )}
                      onClick={() => field.sortable !== false && handleSort(field.key)}
                    >
                      <div className="flex items-center gap-1">
                        {field.label}
                        {field.sortable !== false && sortField === field.key && (
                          <span className="text-xs">
                            {sortDirection === 'asc' ? '↑' : '↓'}
                          </span>
                        )}
                      </div>
                    </TableHead>
                  ))}
                  <TableHead className="w-24">Действия</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {sortedData.map((item) => (
                  <TableRow key={String(item.id)}>
                    {onBulkDelete && (
                      <TableCell>
                        <Checkbox
                          checked={selectedIds.includes(item.id)}
                          onCheckedChange={() => toggleSelection(item.id)}
                        />
                      </TableCell>
                    )}
                    {fields.map((field) => (
                      <TableCell key={String(field.key)}>
                        {renderCellValue(field, item)}
                      </TableCell>
                    ))}
                    <TableCell>
                      <div className="flex items-center gap-1">
                        {editingId === item.id ? (
                          <>
                            <Button
                              variant="ghost"
                              size="icon"
                              className="h-8 w-8"
                              onClick={saveEditing}
                            >
                              <Save className="h-4 w-4" />
                            </Button>
                            <Button
                              variant="ghost"
                              size="icon"
                              className="h-8 w-8"
                              onClick={cancelEditing}
                            >
                              <X className="h-4 w-4" />
                            </Button>
                          </>
                        ) : (
                          <>
                            <Button
                              variant="ghost"
                              size="icon"
                              className="h-8 w-8"
                              onClick={() => startEditing(item)}
                            >
                              <Edit2 className="h-4 w-4" />
                            </Button>
                            <Button
                              variant="ghost"
                              size="icon"
                              className="h-8 w-8 text-red-600"
                              onClick={() => setDeleteConfirmId(item.id)}
                            >
                              <Trash2 className="h-4 w-4" />
                            </Button>
                            {customActions && customActions(item)}
                          </>
                        )}
                      </div>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>
        )}
      </CardContent>

      {/* Add Dialog */}
      <Dialog open={isAddDialogOpen} onOpenChange={setIsAddDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Добавить запись</DialogTitle>
            <DialogDescription>
              Заполните поля для создания новой записи
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4 py-4">
            {fields.map((field) => {
              if (field.type === 'custom' && field.renderEdit) {
                return (
                  <div key={String(field.key)}>
                    <label className="text-sm font-medium">{field.label}</label>
                    {field.renderEdit(
                      newItemData[field.key],
                      (value) => setNewItemData({ ...newItemData, [field.key]: value }),
                      {} as T
                    )}
                  </div>
                );
              }

              return (
                <div key={String(field.key)}>
                  <label className="text-sm font-medium">
                    {field.label}
                    {field.required && <span className="text-red-500 ml-1">*</span>}
                  </label>
                  {field.type === 'select' ? (
                    <select
                      value={newItemData[field.key] || ''}
                      onChange={(e) => setNewItemData({
                        ...newItemData,
                        [field.key]: e.target.value
                      })}
                      className="mt-1 w-full rounded border p-2"
                    >
                      <option value="">Выберите...</option>
                      {field.options?.map(option => (
                        <option key={option.value} value={option.value}>
                          {option.label}
                        </option>
                      ))}
                    </select>
                  ) : field.type === 'boolean' ? (
                    <div className="mt-1">
                      <Checkbox
                        checked={newItemData[field.key] || false}
                        onCheckedChange={(checked) => setNewItemData({
                          ...newItemData,
                          [field.key]: checked
                        })}
                      />
                    </div>
                  ) : (
                    <Input
                      type={field.type}
                      value={newItemData[field.key] || ''}
                      onChange={(e) => setNewItemData({
                        ...newItemData,
                        [field.key]: field.type === 'number' ? Number(e.target.value) : e.target.value
                      })}
                      className="mt-1"
                    />
                  )}
                </div>
              );
            })}
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setIsAddDialogOpen(false)}>
              Отмена
            </Button>
            <Button onClick={handleAdd}>
              Добавить
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Delete Confirmation */}
      <AlertDialog open={!!deleteConfirmId} onOpenChange={() => setDeleteConfirmId(null)}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Подтверждение удаления</AlertDialogTitle>
            <AlertDialogDescription>
              Вы уверены, что хотите удалить эту запись? Это действие нельзя отменить.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Отмена</AlertDialogCancel>
            <AlertDialogAction onClick={handleDelete} className="bg-red-600 hover:bg-red-700">
              Удалить
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

      {/* Bulk Delete Confirmation */}
      <AlertDialog open={bulkDeleteConfirm} onOpenChange={setBulkDeleteConfirm}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Подтверждение удаления</AlertDialogTitle>
            <AlertDialogDescription>
              Вы уверены, что хотите удалить {selectedIds.length} записей? Это действие нельзя отменить.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Отмена</AlertDialogCancel>
            <AlertDialogAction onClick={handleBulkDelete} className="bg-red-600 hover:bg-red-700">
              Удалить все
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </Card>
  );
}
