// frontend-svelte/src/lib/components/reference/PeriodManager.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  // TODO: Replace with SimpleDataTable when needed
  // import { createColumnHelper, type ColumnDef } from '@tanstack/svelte-table';
  import { currentUser } from '$lib/stores/auth.store';
  import { useToast } from '$lib/stores/toast.store';
  import { periodsService, type CreatePeriodData, type UpdatePeriodData } from '$lib/services/periods.service';
  import type { Period } from '$types';
  
  import CRUDTable from '$lib/components/common/CRUDTable.svelte';
  import Modal from '$lib/components/ui/Modal.svelte';
  import Button from '$lib/components/ui/Button.svelte';
  import Input from '$lib/components/ui/Input.svelte';
  import Badge from '$lib/components/ui/Badge.svelte';

  let periods: Period[] = [];
  let loading = true;
  let showModal = false;
  let editingPeriod: Period | null = null;
  let isEditing = false;

  // Form state
  let formData = {
    period_name: '',
    period_year: new Date().getFullYear(),
    period_month: new Date().getMonth() + 1,
    period_order: 1,
    is_active: true
  };

  let formErrors: Record<string, string> = {};

  const toast = useToast();

  const monthNames = [
    'Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь',
    'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь'
  ];

  // Define table columns for CRUDTable
  const columns = [
    {
      key: 'period_name',
      header: 'Название периода',
      sortable: true
    },
    {
      key: 'period_year',
      header: 'Год',
      sortable: true
    },
    {
      key: 'period_month',
      header: 'Месяц',
      sortable: true,
      render: (item: Period) => monthNames[item.period_month - 1] || '-'
    },
    {
      key: 'period_order',
      header: 'Порядок',
      sortable: true
    },
    {
      key: 'is_active',
      header: 'Статус',
      render: (item: Period) => item.is_active ? 'Активен' : 'Неактивен'
    },
    {
      key: 'created_at',
      header: 'Создан',
      sortable: true,
      render: (item: Period) => {
        if (!item.created_at) return '-';
        return new Date(item.created_at).toLocaleDateString('ru-RU', {
          day: '2-digit',
          month: '2-digit',
          year: 'numeric',
        });
      }
    }
  ];

  // Load periods
  async function fetchPeriods() {
    if (!$currentUser?.user_id) return;
    
    try {
      loading = true;
      periods = await periodsService.getByUserId($currentUser.user_id);
    } catch (error: any) {
      toast.error('Ошибка', 'Не удалось загрузить периоды');
      console.error('Error fetching periods:', error);
    } finally {
      loading = false;
    }
  }

  onMount(() => {
    fetchPeriods();
  });

  // Form validation
  function validateForm(): boolean {
    formErrors = {};

    if (!formData.period_name || formData.period_name.trim().length < 3) {
      formErrors.period_name = 'Название должно содержать минимум 3 символа';
    }

    if (formData.period_year < 2020 || formData.period_year > 2030) {
      formErrors.period_year = 'Год должен быть между 2020 и 2030';
    }

    if (formData.period_order < 1) {
      formErrors.period_order = 'Порядок должен быть больше 0';
    }

    return Object.keys(formErrors).length === 0;
  }

  // Handle add
  function handleAdd() {
    isEditing = false;
    editingPeriod = null;
    formData = {
      period_name: '',
      period_year: new Date().getFullYear(),
      period_month: new Date().getMonth() + 1,
      period_order: Math.max(...periods.map(p => p.period_order), 0) + 1,
      is_active: true
    };
    formErrors = {};
    showModal = true;
  }

  // Handle edit
  function handleEdit(event: CustomEvent) {
    const { item } = event.detail;
    isEditing = true;
    editingPeriod = item;
    formData = {
      period_name: item.period_name,
      period_year: item.period_year,
      period_month: item.period_month,
      period_order: item.period_order,
      is_active: item.is_active ?? true
    };
    formErrors = {};
    showModal = true;
  }

  // Handle delete
  async function handleDelete(event: CustomEvent) {
    const { id } = event.detail;
    
    try {
      await periodsService.delete(id);
      await fetchPeriods();
      toast.success('Успешно', 'Период удален');
    } catch (error: any) {
      toast.error('Ошибка', error.message || 'Не удалось удалить период');
    }
  }

  // Handle bulk delete
  async function handleBulkDelete(event: CustomEvent) {
    const { ids } = event.detail;
    
    try {
      await periodsService.bulkDelete(ids);
      await fetchPeriods();
      toast.success('Успешно', `Удалено периодов: ${ids.length}`);
    } catch (error: any) {
      toast.error('Ошибка', error.message || 'Не удалось удалить периоды');
    }
  }

  // Handle form submit
  async function handleSubmit() {
    if (!validateForm()) {
      return;
    }

    if (!$currentUser?.user_id) {
      toast.error('Ошибка', 'Пользователь не авторизован');
      return;
    }

    try {
      if (isEditing && editingPeriod) {
        const updateData: UpdatePeriodData = { ...formData };
        await periodsService.update(editingPeriod.period_id, updateData);
        toast.success('Успешно', 'Период обновлен');
      } else {
        const createData: CreatePeriodData = {
          ...formData,
          user_id: $currentUser.user_id
        };
        await periodsService.create(createData);
        toast.success('Успешно', 'Период создан');
      }
      
      await fetchPeriods();
      showModal = false;
    } catch (error: any) {
      toast.error('Ошибка', error.message || 'Не удалось сохранить период');
    }
  }

  // Handle export
  async function handleExport() {
    try {
      const csvContent = await periodsService.exportToCsv(periods);
      const blob = new Blob(['\ufeff' + csvContent], { type: 'text/csv;charset=utf-8;' });
      const link = document.createElement('a');
      link.href = URL.createObjectURL(blob);
      link.download = `periods_${new Date().toISOString().split('T')[0]}.csv`;
      link.click();
      toast.success('Успешно', 'Данные экспортированы');
    } catch (error: any) {
      toast.error('Ошибка', 'Не удалось экспортировать данные');
    }
  }

  // Handle import
  async function handleImport(event: CustomEvent) {
    const { file } = event.detail;
    
    if (!$currentUser?.user_id) {
      toast.error('Ошибка', 'Пользователь не авторизован');
      return;
    }

    try {
      const text = await file.text();
      const importData = await periodsService.importFromCsv(text, $currentUser.user_id);
      
      // Import each period
      for (const periodData of importData) {
        await periodsService.create(periodData);
      }
      
      await fetchPeriods();
      toast.success('Успешно', `Импортировано периодов: ${importData.length}`);
    } catch (error: any) {
      toast.error('Ошибка', error.message || 'Не удалось импортировать данные');
    }
  }

  function handleCloseModal() {
    showModal = false;
    formErrors = {};
  }
</script>

<CRUDTable
  title="Управление периодами"
  {data: periods}
  {columns}
  {loading}
  searchable={true}
  exportable={true}
  importable={true}
  addButtonText="Добавить период"
  emptyMessage="Нет добавленных периодов. Нажмите 'Добавить период' для создания нового."
  on:add={handleAdd}
  on:edit={handleEdit}
  on:delete={handleDelete}
  on:bulkDelete={handleBulkDelete}
  on:export={handleExport}
  on:import={handleImport}
/>

<Modal 
  bind:open={showModal}
  title={isEditing ? 'Редактировать период' : 'Добавить период'}
  on:close={handleCloseModal}
>
  <form on:submit|preventDefault={handleSubmit} class="space-y-4">
    <div>
      <label for="period_name" class="block text-sm font-medium text-gray-700 mb-1">
        Название периода *
      </label>
      <Input
        id="period_name"
        bind:value={formData.period_name}
        placeholder="Введите название периода"
        class={formErrors.period_name ? 'border-red-500' : ''}
      />
      {#if formErrors.period_name}
        <p class="text-red-500 text-xs mt-1">{formErrors.period_name}</p>
      {/if}
    </div>

    <div class="grid grid-cols-2 gap-4">
      <div>
        <label for="period_year" class="block text-sm font-medium text-gray-700 mb-1">
          Год *
        </label>
        <Input
          id="period_year"
          type="number"
          min="2020"
          max="2030"
          bind:value={formData.period_year}
          class={formErrors.period_year ? 'border-red-500' : ''}
        />
        {#if formErrors.period_year}
          <p class="text-red-500 text-xs mt-1">{formErrors.period_year}</p>
        {/if}
      </div>

      <div>
        <label for="period_month" class="block text-sm font-medium text-gray-700 mb-1">
          Месяц *
        </label>
        <select
          id="period_month"
          bind:value={formData.period_month}
          class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
        >
          {#each monthNames as month, index}
            <option value={index + 1}>{month}</option>
          {/each}
        </select>
      </div>
    </div>

    <div>
      <label for="period_order" class="block text-sm font-medium text-gray-700 mb-1">
        Порядок *
      </label>
      <Input
        id="period_order"
        type="number"
        min="1"
        bind:value={formData.period_order}
        class={formErrors.period_order ? 'border-red-500' : ''}
      />
      {#if formErrors.period_order}
        <p class="text-red-500 text-xs mt-1">{formErrors.period_order}</p>
      {/if}
    </div>

    <div class="flex items-center">
      <input
        id="is_active"
        type="checkbox"
        bind:checked={formData.is_active}
        class="h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-300 rounded"
      />
      <label for="is_active" class="ml-2 block text-sm text-gray-900">
        Активен
      </label>
    </div>
  </form>

  <svelte:fragment slot="footer">
    <Button variant="outline" on:click={handleCloseModal}>
      Отмена
    </Button>
    <Button type="submit" on:click={handleSubmit}>
      {isEditing ? 'Обновить' : 'Создать'}
    </Button>
  </svelte:fragment>
</Modal>

// frontend/src/components/reference/PeriodManager.tsx
import React, { useState, useEffect } from 'react';
import { CRUDTable, type CRUDField } from './CRUDTable';
import { Badge } from '../ui/badge';
import { toast } from '../ui/use-toast';
import { useAuthStore } from '../../stores/authStore';
import { apiClient } from '../../api/client';

interface Period {
  id: number;
  period_id: number;
  period_name: string;
  period_year: number;
  period_month: number;
  period_order: number;
  user_id: number;
  is_active?: boolean;
  created_at?: string;
  updated_at?: string;
}

const monthNames = [
  'Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь',
  'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь'
];

export const PeriodManager: React.FC = () => {
  const [periods, setPeriods] = useState<Period[]>([]);
  const [loading, setLoading] = useState(true);
  const { user } = useAuthStore();

  // Define fields for CRUD table
  const fields: CRUDField<Period>[] = [
    {
      key: 'period_name',
      label: 'Название периода',
      type: 'text',
      required: true,
      width: 'w-64',
      validation: (value) => {
        if (!value || value.trim().length < 3) {
          return 'Название должно содержать минимум 3 символа';
        }
        return null;
      },
    },
    {
      key: 'period_year',
      label: 'Год',
      type: 'number',
      required: true,
      width: 'w-24',
      validation: (value) => {
        const year = Number(value);
        if (year < 2020 || year > 2030) {
          return 'Год должен быть между 2020 и 2030';
        }
        return null;
      },
    },
    {
      key: 'period_month',
      label: 'Месяц',
      type: 'select',
      required: true,
      width: 'w-32',
      options: monthNames.map((name, index) => ({
        value: String(index + 1),
        label: name,
      })),
      renderCell: (value) => monthNames[value - 1] || '-',
    },
    {
      key: 'period_order',
      label: 'Порядок',
      type: 'number',
      required: true,
      width: 'w-24',
      validation: (value) => {
        if (Number(value) < 1) {
          return 'Порядок должен быть больше 0';
        }
        return null;
      },
    },
    {
      key: 'is_active',
      label: 'Активен',
      type: 'boolean',
      width: 'w-24',
      renderCell: (value) => value ? (
        <Badge variant="default">Активен</Badge>
      ) : (
        <Badge variant="secondary">Неактивен</Badge>
      ),
    },
    {
      key: 'created_at',
      label: 'Создан',
      type: 'date',
      width: 'w-32',
      sortable: true,
      filterable: false,
      renderCell: (value) => {
        if (!value) return '-';
        return new Date(value).toLocaleDateString('ru-RU', {
          day: '2-digit',
          month: '2-digit',
          year: 'numeric',
        });
      },
      renderEdit: () => null, // Read-only in edit mode
    },
  ];

  // Fetch periods
  const fetchPeriods = async () => {
    if (!user?.user_id) return;
    
    try {
      setLoading(true);
      const response = await apiClient.get(`/periods?user_id=${user.user_id}`);
      setPeriods(response.data.map((p: any) => ({
        ...p,
        id: p.period_id, // Map period_id to id for CRUD table
      })));
    } catch (error) {
      toast({
        title: 'Ошибка',
        description: 'Не удалось загрузить периоды',
        variant: 'destructive',
      });
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchPeriods();
  }, [user]);

  // Add period
  const handleAdd = async (data: Omit<Period, 'id'>) => {
    if (!user?.user_id) return;
    
    const newPeriod = {
      ...data,
      user_id: user.user_id,
      period_month: Number(data.period_month),
      is_active: data.is_active || true,
    };

    try {
      await apiClient.post('/periods', newPeriod);
      await fetchPeriods();
    } catch (error: any) {
      throw new Error(error.response?.data?.detail || 'Не удалось добавить период');
    }
  };

  // Update period
  const handleUpdate = async (id: number, data: Partial<Period>) => {
    const updateData = {
      ...data,
      period_month: data.period_month ? Number(data.period_month) : undefined,
    };

    try {
      await apiClient.put(`/periods/${id}`, updateData);
      await fetchPeriods();
    } catch (error: any) {
      throw new Error(error.response?.data?.detail || 'Не удалось обновить период');
    }
  };

  // Delete period
  const handleDelete = async (id: number) => {
    try {
      await apiClient.delete(`/periods/${id}`);
      await fetchPeriods();
    } catch (error: any) {
      throw new Error(error.response?.data?.detail || 'Не удалось удалить период');
    }
  };

  // Bulk delete periods
  const handleBulkDelete = async (ids: number[]) => {
    try {
      // API doesn't support bulk delete, so we'll delete one by one
      await Promise.all(ids.map(id => apiClient.delete(`/periods/${id}`)));
      await fetchPeriods();
    } catch (error: any) {
      throw new Error(error.response?.data?.detail || 'Не удалось удалить периоды');
    }
  };

  // Export periods
  const handleExport = () => {
    const csvContent = [
      ['ID', 'Название', 'Год', 'Месяц', 'Порядок', 'Активен', 'Создан'].join(','),
      ...periods.map(p => [
        p.period_id,
        `"${p.period_name}"`,
        p.period_year,
        p.period_month,
        p.period_order,
        p.is_active ? 'Да' : 'Нет',
        p.created_at ? new Date(p.created_at).toLocaleDateString('ru-RU') : '',
      ].join(','))
    ].join('\n');

    const blob = new Blob(['\ufeff' + csvContent], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.download = `periods_${new Date().toISOString().split('T')[0]}.csv`;
    link.click();
  };

  // Import periods
  const handleImport = async (file: File) => {
    const text = await file.text();
    const lines = text.split('\n').slice(1); // Skip header
    
    const newPeriods: Omit<Period, 'id'>[] = [];
    
    for (const line of lines) {
      if (!line.trim()) continue;
      
      const [, name, year, month, order, isActive] = line.split(',').map(v => v.replace(/"/g, '').trim());
      
      newPeriods.push({
        period_name: name,
        period_year: Number(year),
        period_month: Number(month),
        period_order: Number(order),
        is_active: isActive === 'Да',
        user_id: user!.user_id,
      } as Omit<Period, 'id'>);
    }

    // Add periods one by one
    for (const period of newPeriods) {
      await handleAdd(period);
    }
  };

  return (
    <CRUDTable
      title="Управление периодами"
      data={periods}
      fields={fields}
      onAdd={handleAdd}
      onUpdate={handleUpdate}
      onDelete={handleDelete}
      onBulkDelete={handleBulkDelete}
      loading={loading}
      searchable={true}
      exportable={true}
      importable={true}
      onExport={handleExport}
      onImport={handleImport}
      emptyMessage="Нет добавленных периодов. Нажмите 'Добавить период' для создания нового."
      addButtonText="Добавить период"
    />
  );
};
