// frontend/src/components/products/ProductForm.tsx
import React, { useState } from 'react';
import { useForm } from 'react-hook-form';
import { Card } from '../common/Card';
import { Input } from '../common/form/Input';
import { Button } from '../common/form/Button';
import { TextArea } from '../common/form/TextArea';
import { useToast } from '../common/ToastContainer';
import type { Product } from '../../types';
import { productService, type CreateProductData, type UpdateProductData } from '../../services';

interface ProductFormProps {
  onSuccess?: () => void;
  product?: Product;
  onCancel?: () => void;
}

interface ProductFormData {
  product_name: string;
  category_name: string;
  unit_measure: string;
  barcode?: string;
  description?: string;
  is_active: boolean;
}

export const ProductForm: React.FC<ProductFormProps> = ({ 
  onSuccess, 
  product,
  onCancel 
}) => {
  const [isSubmitting, setIsSubmitting] = useState(false);
  const toast = useToast();
  
  const {
    register,
    handleSubmit,
    formState: { errors },
    reset,
  } = useForm<ProductFormData>({
    defaultValues: product ? {
      product_name: product.product_name,
      category_name: product.category_name || '',
      unit_measure: product.unit_measure || '',
      barcode: product.barcode || '',
      description: product.description || '',
      is_active: product.is_active,
    } : {
      is_active: true,
    },
  });

  const onSubmit = async (data: ProductFormData) => {
    setIsSubmitting(true);
    
    try {
      if (product) {
        const updateData: UpdateProductData = {
          product_name: data.product_name,
          category_name: data.category_name,
          unit_measure: data.unit_measure,
          barcode: data.barcode,
          description: data.description,
          is_active: data.is_active,
        };
        await productService.update(product.product_id!, updateData);
        toast.success('Успешно', 'Продукт обновлен');
      } else {
        const createData: CreateProductData = {
          product_name: data.product_name,
          category_name: data.category_name,
          unit_measure: data.unit_measure,
          barcode: data.barcode,
          description: data.description,
          is_active: data.is_active,
        };
        await productService.create(createData);
        toast.success('Успешно', 'Продукт добавлен');
      }
      reset();
      onSuccess?.();
    } catch (error: any) {
      console.error('Ошибка при сохранении продукта:', error);
      toast.error('Ошибка', error.message || 'Не удалось сохранить продукт');
    } finally {
      setIsSubmitting(false);
    }
  };

  const categoryOptions = [
    { value: 'Продукты питания', label: 'Продукты питания' },
    { value: 'Напитки', label: 'Напитки' },
    { value: 'Бытовая химия', label: 'Бытовая химия' },
    { value: 'Косметика', label: 'Косметика' },
    { value: 'Одежда', label: 'Одежда' },
    { value: 'Электроника', label: 'Электроника' },
    { value: 'Другое', label: 'Другое' },
  ];

  const unitOptions = [
    { value: 'шт', label: 'штуки' },
    { value: 'кг', label: 'килограммы' },
    { value: 'г', label: 'граммы' },
    { value: 'л', label: 'литры' },
    { value: 'мл', label: 'миллилитры' },
    { value: 'упак', label: 'упаковки' },
    { value: 'м', label: 'метры' },
    { value: 'см', label: 'сантиметры' },
  ];

  return (
    <Card title={product ? 'Редактировать продукт' : 'Добавить продукт'}>
      <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
        <Input
          label="Наименование продукта"
          {...register('product_name', {
            required: 'Наименование обязательно',
          })}
          error={errors.product_name?.message}
        />

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              Категория <span className="text-red-500">*</span>
            </label>
            <select
              {...register('category_name', {
                required: 'Выберите категорию',
              })}
              className="block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500 sm:text-sm"
            >
              <option value="">Выберите категорию</option>
              {categoryOptions.map(option => (
                <option key={option.value} value={option.value}>{option.label}</option>
              ))}
            </select>
            {errors.category_name && (
              <p className="mt-1 text-sm text-red-600">{errors.category_name.message}</p>
            )}
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              Единица измерения <span className="text-red-500">*</span>
            </label>
            <select
              {...register('unit_measure', {
                required: 'Выберите единицу измерения',
              })}
              className="block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500 sm:text-sm"
            >
              <option value="">Выберите единицу</option>
              {unitOptions.map(option => (
                <option key={option.value} value={option.value}>{option.label}</option>
              ))}
            </select>
            {errors.unit_measure && (
              <p className="mt-1 text-sm text-red-600">{errors.unit_measure.message}</p>
            )}
          </div>
        </div>

        <Input
          label="Штрихкод"
          {...register('barcode')}
          error={errors.barcode?.message}
        />

        <TextArea
          label="Описание"
          rows={3}
          {...register('description')}
          error={errors.description?.message}
        />

        <div className="flex items-center gap-2">
          <input
            type="checkbox"
            id="is_active"
            {...register('is_active')}
            className="rounded border-gray-300"
          />
          <label htmlFor="is_active" className="text-sm font-medium text-gray-700">
            Активный продукт
          </label>
        </div>

        <div className="flex gap-3">
          <Button
            type="submit"
            variant="default"
            disabled={isSubmitting}
            className="flex-1"
          >
            {isSubmitting 
              ? 'Сохранение...' 
              : product ? 'Обновить' : 'Добавить'
            }
          </Button>
          <Button
            type="button"
            variant="secondary"
            onClick={onCancel || (() => reset())}
            disabled={isSubmitting}
          >
            {onCancel ? 'Отмена' : 'Очистить'}
          </Button>
        </div>
      </form>
    </Card>
  );
};

// frontend-svelte/src/lib/components/products/ProductForm.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  import { productService, type Product, type CreateProductData, type UpdateProductData } from '$lib/services/product.service';
  import { toastStore } from '$lib/stores/toast.store';
  import Card from '$lib/components/ui/Card.svelte';
  import Input from '$lib/components/ui/Input.svelte';
  import Button from '$lib/components/ui/Button.svelte';

  export let product: Product | null = null;
  export let onCancel: (() => void) | null = null;

  const dispatch = createEventDispatcher<{
    success: void;
  }>();

  let isSubmitting = false;
  
  // Форма данных
  let formData = {
    product_name: product?.product_name || '',
    category_name: product?.category_name || '',
    unit_measure: product?.unit_measure || '',
    barcode: product?.barcode || '',
    description: product?.description || '',
    is_active: product?.is_active ?? true
  };

  // Ошибки валидации
  let errors: { [key: string]: string } = {};

  const categoryOptions = [
    { value: 'Продукты питания', label: 'Продукты питания' },
    { value: 'Напитки', label: 'Напитки' },
    { value: 'Бытовая химия', label: 'Бытовая химия' },
    { value: 'Косметика', label: 'Косметика' },
    { value: 'Одежда', label: 'Одежда' },
    { value: 'Электроника', label: 'Электроника' },
    { value: 'Другое', label: 'Другое' },
  ];

  const unitOptions = [
    { value: 'шт', label: 'штуки' },
    { value: 'кг', label: 'килограммы' },
    { value: 'г', label: 'граммы' },
    { value: 'л', label: 'литры' },
    { value: 'мл', label: 'миллилитры' },
    { value: 'упак', label: 'упаковки' },
    { value: 'м', label: 'метры' },
    { value: 'см', label: 'сантиметры' },
  ];

  function validateForm() {
    errors = {};
    
    if (!formData.product_name.trim()) {
      errors.product_name = 'Наименование обязательно';
    }
    
    if (!formData.category_name) {
      errors.category_name = 'Выберите категорию';
    }
    
    if (!formData.unit_measure) {
      errors.unit_measure = 'Выберите единицу измерения';
    }

    return Object.keys(errors).length === 0;
  }

  async function handleSubmit() {
    if (!validateForm()) {
      return;
    }

    isSubmitting = true;
    
    try {
      if (product) {
        // Обновление существующего продукта
        const updateData: UpdateProductData = {
          product_name: formData.product_name,
          category_name: formData.category_name,
          unit_measure: formData.unit_measure,
          barcode: formData.barcode || undefined,
          description: formData.description || undefined,
          is_active: formData.is_active,
        };
        await productService.update(product.product_id!, updateData);
        toastStore.success('Продукт обновлен');
      } else {
        // Создание нового продукта
        const createData: CreateProductData = {
          product_name: formData.product_name,
          category_name: formData.category_name,
          unit_measure: formData.unit_measure,
          barcode: formData.barcode || undefined,
          description: formData.description || undefined,
          is_active: formData.is_active,
        };
        await productService.create(createData);
        toastStore.success('Продукт добавлен');
      }
      
      resetForm();
      dispatch('success');
    } catch (error: any) {
      console.error('Ошибка при сохранении продукта:', error);
      toastStore.error(error.message || 'Не удалось сохранить продукт');
    } finally {
      isSubmitting = false;
    }
  }

  function resetForm() {
    if (!product) {
      formData = {
        product_name: '',
        category_name: '',
        unit_measure: '',
        barcode: '',
        description: '',
        is_active: true
      };
    }
    errors = {};
  }

  function handleCancel() {
    if (onCancel) {
      onCancel();
    } else {
      resetForm();
    }
  }
</script>

<Card title={product ? 'Редактировать продукт' : 'Добавить продукт'}>
  <form on:submit|preventDefault={handleSubmit} class="space-y-6">
    <Input
      label="Наименование продукта"
      bind:value={formData.product_name}
      error={errors.product_name}
      required
    />

    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
      <div>
        <label for="category" class="block text-sm font-medium text-gray-700 mb-1">
          Категория <span class="text-red-500">*</span>
        </label>
        <select
          id="category"
          bind:value={formData.category_name}
          class="block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500 sm:text-sm"
          class:border-red-500={errors.category_name}
        >
          <option value="">Выберите категорию</option>
          {#each categoryOptions as option}
            <option value={option.value}>{option.label}</option>
          {/each}
        </select>
        {#if errors.category_name}
          <p class="mt-1 text-sm text-red-600">{errors.category_name}</p>
        {/if}
      </div>

      <div>
        <label for="unit_measure" class="block text-sm font-medium text-gray-700 mb-1">
          Единица измерения <span class="text-red-500">*</span>
        </label>
        <select
          id="unit_measure"
          bind:value={formData.unit_measure}
          class="block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500 sm:text-sm"
          class:border-red-500={errors.unit_measure}
        >
          <option value="">Выберите единицу</option>
          {#each unitOptions as option}
            <option value={option.value}>{option.label}</option>
          {/each}
        </select>
        {#if errors.unit_measure}
          <p class="mt-1 text-sm text-red-600">{errors.unit_measure}</p>
        {/if}
      </div>
    </div>

    <Input
      label="Штрихкод"
      bind:value={formData.barcode}
      error={errors.barcode}
    />

    <div>
      <label for="description" class="block text-sm font-medium text-gray-700 mb-1">
        Описание
      </label>
      <textarea
        id="description"
        bind:value={formData.description}
        rows="3"
        class="block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500 sm:text-sm"
        class:border-red-500={errors.description}
      />
      {#if errors.description}
        <p class="mt-1 text-sm text-red-600">{errors.description}</p>
      {/if}
    </div>

    <div class="flex items-center gap-2">
      <input
        type="checkbox"
        id="is_active"
        bind:checked={formData.is_active}
        class="rounded border-gray-300"
      />
      <label for="is_active" class="text-sm font-medium text-gray-700">
        Активный продукт
      </label>
    </div>

    <div class="flex gap-3">
      <Button
        type="submit"
        disabled={isSubmitting}
        class="flex-1"
      >
        {isSubmitting 
          ? 'Сохранение...' 
          : product ? 'Обновить' : 'Добавить'
        }
      </Button>
      <Button
        type="button"
        variant="secondary"
        on:click={handleCancel}
        disabled={isSubmitting}
      >
        {onCancel ? 'Отмена' : 'Очистить'}
      </Button>
    </div>
  </form>
</Card>
