// frontend/src/components/fact/FactList.tsx
import React, { useState, useEffect } from 'react';
import { 
  Card, 
  CardContent, 
  CardHeader, 
  CardTitle,
  CardDescription 
} from '../ui/card';
import { 
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '../ui/table';
import { Button } from '../ui/button';
import { Badge } from '../ui/badge';
import { Skeleton } from '../ui/skeleton';
import { useToast } from '../common/ToastContainer';
import { registryService } from '../../services';
import type { Registry } from '../../types';
import { 
  Calendar,
  Building,
  Tag,
  DollarSign,
  MessageSquare,
  Trash2,
  Edit,
  Eye,
  RefreshCw
} from 'lucide-react';

interface ExtendedRegistry extends Registry {
  period_name?: string;
  financial_center_name?: string;
  cost_center_name?: string;
  nomenclature_name?: string;
}

export const FactList: React.FC = () => {
  const [facts, setFacts] = useState<ExtendedRegistry[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isRefreshing, setIsRefreshing] = useState(false);
  const toast = useToast();

  useEffect(() => {
    loadFacts();
  }, []);

  const loadFacts = async () => {
    try {
      setIsLoading(true);
      const data = await registryService.getFacts({ limit: 50 });
      setFacts(data);
    } catch (error) {
      console.error('Ошибка загрузки расходов:', error);
      toast.error('Ошибка', error instanceof Error ? error.message : 'Не удалось загрузить список расходов');
    } finally {
      setIsLoading(false);
    }
  };

  const handleRefresh = async () => {
    setIsRefreshing(true);
    await loadFacts();
    setIsRefreshing(false);
  };

  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('ru-RU', {
      style: 'currency',
      currency: 'RUB',
    }).format(amount);
  };

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('ru-RU');
  };

  const LoadingSkeleton = () => (
    <div className="space-y-3">
      {[...Array(5)].map((_, i) => (
        <div key={i} className="flex space-x-4">
          <Skeleton className="h-4 w-20" />
          <Skeleton className="h-4 w-32" />
          <Skeleton className="h-4 w-24" />
          <Skeleton className="h-4 w-20" />
          <Skeleton className="h-4 w-40" />
          <Skeleton className="h-4 w-24" />
        </div>
      ))}
    </div>
  );

  return (
    <Card className="border-l-4 border-l-red-500">
      <CardHeader className="bg-gradient-to-r from-red-50 to-orange-50">
        <div className="flex items-center justify-between">
          <div>
            <CardTitle className="flex items-center gap-2">
              <div className="h-10 w-10 bg-red-100 rounded-full flex items-center justify-center">
                <DollarSign className="h-5 w-5 text-red-600" />
              </div>
              История операций
            </CardTitle>
            <CardDescription>
              Последние фактические расходы и доходы
            </CardDescription>
          </div>
          <Button
            variant="outline"
            size="sm"
            onClick={handleRefresh}
            disabled={isRefreshing}
          >
            <RefreshCw className={`h-4 w-4 mr-2 ${isRefreshing ? 'animate-spin' : ''}`} />
            Обновить
          </Button>
        </div>
      </CardHeader>
      
      <CardContent>
        {isLoading ? (
          <LoadingSkeleton />
        ) : facts.length === 0 ? (
          <div className="text-center py-8">
            <DollarSign className="h-12 w-12 text-slate-300 mx-auto mb-4" />
            <p className="text-slate-500 mb-2">Расходы не найдены</p>
            <p className="text-sm text-slate-400">
              Добавьте первую операцию, чтобы увидеть ее здесь
            </p>
          </div>
        ) : (
          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <Badge variant="secondary" className="text-sm">
                Всего операций: {facts.length}
              </Badge>
              <Badge variant="outline" className="text-sm">
                Сумма: {formatCurrency(facts.reduce((sum, fact) => sum + fact.cost_sum, 0))}
              </Badge>
            </div>
            
            <div className="rounded-md border">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead className="w-24">
                      <div className="flex items-center gap-1">
                        <Calendar className="h-4 w-4" />
                        Дата
                      </div>
                    </TableHead>
                    <TableHead>Период</TableHead>
                    <TableHead>
                      <div className="flex items-center gap-1">
                        <Building className="h-4 w-4" />
                        ФЦ
                      </div>
                    </TableHead>
                    <TableHead>МВЗ</TableHead>
                    <TableHead>
                      <div className="flex items-center gap-1">
                        <Tag className="h-4 w-4" />
                        Номенклатура
                      </div>
                    </TableHead>
                    <TableHead className="text-right">
                      <div className="flex items-center justify-end gap-1">
                        <DollarSign className="h-4 w-4" />
                        Сумма
                      </div>
                    </TableHead>
                    <TableHead>
                      <div className="flex items-center gap-1">
                        <MessageSquare className="h-4 w-4" />
                        Комментарий
                      </div>
                    </TableHead>
                    <TableHead className="w-20">Действия</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {facts.map((fact, index) => (
                    <TableRow key={fact.registry_id || index} className="hover:bg-slate-50">
                      <TableCell className="font-medium">
                        {formatDate(fact.operation_dttm)}
                      </TableCell>
                      <TableCell>
                        <Badge variant="outline" className="text-xs">
                          {fact.period_name || 'Не указан'}
                        </Badge>
                      </TableCell>
                      <TableCell>
                        <span className="text-sm text-slate-600">
                          {fact.financial_center_name || '—'}
                        </span>
                      </TableCell>
                      <TableCell>
                        <span className="text-sm text-slate-600">
                          {fact.cost_center_name || '—'}
                        </span>
                      </TableCell>
                      <TableCell>
                        <Badge variant="secondary" className="text-xs">
                          {fact.nomenclature_name || 'Не указано'}
                        </Badge>
                      </TableCell>
                      <TableCell className="text-right font-semibold text-red-600">
                        {formatCurrency(fact.cost_sum)}
                      </TableCell>
                      <TableCell>
                        {fact.comment_description ? (
                          <span 
                            className="text-sm text-slate-600 cursor-help" 
                            title={fact.comment_description}
                          >
                            {fact.comment_description.length > 30 
                              ? `${fact.comment_description.substring(0, 30)}...` 
                              : fact.comment_description}
                          </span>
                        ) : (
                          <span className="text-slate-400">—</span>
                        )}
                      </TableCell>
                      <TableCell>
                        <div className="flex items-center gap-1">
                          <Button variant="ghost" size="sm" className="h-8 w-8 p-0">
                            <Eye className="h-3 w-3" />
                          </Button>
                          <Button variant="ghost" size="sm" className="h-8 w-8 p-0">
                            <Edit className="h-3 w-3" />
                          </Button>
                          <Button variant="ghost" size="sm" className="h-8 w-8 p-0 text-red-500 hover:text-red-700">
                            <Trash2 className="h-3 w-3" />
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  );
};

// frontend-svelte/src/lib/components/fact/FactList.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { currentUser } from '$lib/stores/auth.store';
  import { useToast } from '$lib/stores/toast.store';
  import { registryService, type Registry } from '$lib/services/registry.service';
  import Card from '$lib/components/ui/Card.svelte';
  import DataTable from '$lib/components/common/DataTable.svelte';
  import Loading from '$lib/components/common/Loading.svelte';
  import Badge from '$lib/components/ui/Badge.svelte';
  import { 
    CreditCard, 
    Calendar, 
    Building, 
    Tag, 
    DollarSign,
    RefreshCw,
    Receipt,
    TrendingDown,
    TrendingUp,
    Wallet
  } from 'lucide-svelte';

  interface ExtendedRegistry extends Registry {
    period_name?: string;
    financial_center_name?: string;
    cost_center_name?: string;
    nomenclature_name?: string;
  }

  let facts: ExtendedRegistry[] = [];
  let isLoading = true;
  let isRefreshing = false;

  const toast = useToast();

  onMount(() => {
    loadFacts();
  });

  async function loadFacts() {
    try {
      isLoading = true;
      const data = await registryService.getFacts({ limit: 50 });
      facts = data;
    } catch (error: any) {
      console.error('Ошибка загрузки фактов:', error);
      toast.error('Ошибка', error.message || 'Не удалось загрузить фактические операции');
    } finally {
      isLoading = false;
    }
  }

  async function handleRefresh() {
    isRefreshing = true;
    await loadFacts();
    isRefreshing = false;
  }

  function formatCurrency(amount: number) {
    return new Intl.NumberFormat('ru-RU', {
      style: 'currency',
      currency: 'RUB',
    }).format(Math.abs(amount));
  }

  function formatComment(comment: string | null) {
    if (!comment) return '—';
    return comment.length > 50 ? `${comment.substring(0, 50)}...` : comment;
  }

  // Calculate totals
  $: totalExpenses = facts.filter(item => item.cost_sum > 0).reduce((sum, item) => sum + item.cost_sum, 0);
  $: totalIncomes = Math.abs(facts.filter(item => item.cost_sum < 0).reduce((sum, item) => sum + item.cost_sum, 0));
  $: netBalance = totalIncomes - totalExpenses;
</script>

<div class="space-y-6">
  <!-- Summary Cards -->
  <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
    <Card class="border-l-4 border-l-green-500">
      <div class="p-4">
        <div class="flex items-center justify-between">
          <div>
            <p class="text-sm font-medium text-slate-600">Фактические доходы</p>
            <p class="text-xl font-bold text-green-600">
              {formatCurrency(totalIncomes)}
            </p>
          </div>
          <div class="h-10 w-10 bg-green-100 rounded-full flex items-center justify-center">
            <TrendingUp class="h-5 w-5 text-green-600" />
          </div>
        </div>
      </div>
    </Card>

    <Card class="border-l-4 border-l-red-500">
      <div class="p-4">
        <div class="flex items-center justify-between">
          <div>
            <p class="text-sm font-medium text-slate-600">Фактические расходы</p>
            <p class="text-xl font-bold text-red-600">
              {formatCurrency(totalExpenses)}
            </p>
          </div>
          <div class="h-10 w-10 bg-red-100 rounded-full flex items-center justify-center">
            <TrendingDown class="h-5 w-5 text-red-600" />
          </div>
        </div>
      </div>
    </Card>

    <Card class="border-l-4 border-l-purple-500">
      <div class="p-4">
        <div class="flex items-center justify-between">
          <div>
            <p class="text-sm font-medium text-slate-600">Чистый баланс</p>
            <p class="text-xl font-bold {netBalance >= 0 ? 'text-green-600' : 'text-red-600'}">
              {formatCurrency(netBalance)}
            </p>
          </div>
          <div class="h-10 w-10 {netBalance >= 0 ? 'bg-green-100' : 'bg-red-100'} rounded-full flex items-center justify-center">
            <Wallet class="h-5 w-5 {netBalance >= 0 ? 'text-green-600' : 'text-red-600'}" />
          </div>
        </div>
      </div>
    </Card>
  </div>

  <!-- Facts Table -->
  <Card class="border-l-4 border-l-blue-500">
    <div class="bg-gradient-to-r from-blue-50 to-purple-50 p-4 border-b flex items-center justify-between">
      <div class="flex items-center gap-3">
        <div class="h-10 w-10 bg-blue-100 rounded-full flex items-center justify-center">
          <Receipt class="h-5 w-5 text-blue-600" />
        </div>
        <div>
          <h2 class="text-lg font-semibold text-slate-900">Фактические операции</h2>
          <p class="text-sm text-slate-600">Список всех выполненных операций доходов и расходов</p>
        </div>
      </div>
      <button
        on:click={handleRefresh}
        disabled={isRefreshing}
        class="flex items-center gap-2 px-3 py-2 text-sm bg-white border border-slate-200 rounded-md hover:bg-slate-50 disabled:opacity-50"
      >
        <RefreshCw class="h-4 w-4 {isRefreshing ? 'animate-spin' : ''}" />
        Обновить
      </button>
    </div>

    <div class="p-6">
      {#if isLoading}
        <div class="flex justify-center items-center py-12">
          <Loading size="large" text="Загрузка операций..." />
        </div>
      {:else if facts.length === 0}
        <div class="text-center py-12">
          <div class="h-16 w-16 bg-slate-100 rounded-full flex items-center justify-center mx-auto mb-4">
            <Receipt class="h-8 w-8 text-slate-400" />
          </div>
          <h3 class="text-lg font-medium text-slate-900 mb-2">Операций пока нет</h3>
          <p class="text-slate-600 mb-4">Добавьте свою первую фактическую операцию</p>
        </div>
      {:else}
        <div class="overflow-x-auto">
          <table class="w-full">
            <thead>
              <tr class="border-b border-slate-200">
                <th class="text-left py-3 px-4 font-medium text-slate-700">Дата</th>
                <th class="text-left py-3 px-4 font-medium text-slate-700">Период</th>
                <th class="text-left py-3 px-4 font-medium text-slate-700">Тип</th>
                <th class="text-left py-3 px-4 font-medium text-slate-700">Финансовый центр</th>
                <th class="text-left py-3 px-4 font-medium text-slate-700">МВЗ</th>
                <th class="text-left py-3 px-4 font-medium text-slate-700">Номенклатура</th>
                <th class="text-left py-3 px-4 font-medium text-slate-700">Сумма</th>
                <th class="text-left py-3 px-4 font-medium text-slate-700">Комментарий</th>
              </tr>
            </thead>
            <tbody>
              {#each facts as item, index}
                <tr class="border-b border-slate-100 hover:bg-slate-50 transition-colors">
                  <td class="py-3 px-4">
                    {new Date(item.operation_dttm).toLocaleDateString('ru-RU')}
                  </td>
                  <td class="py-3 px-4">
                    {item.period_name || '—'}
                  </td>
                  <td class="py-3 px-4">
                    {#if item.cost_sum > 0}
                      <Badge variant="destructive" class="flex items-center gap-1 w-fit">
                        <TrendingDown class="h-3 w-3" />
                        Расход
                      </Badge>
                    {:else}
                      <Badge variant="success" class="flex items-center gap-1 w-fit">
                        <TrendingUp class="h-3 w-3" />
                        Доход
                      </Badge>
                    {/if}
                  </td>
                  <td class="py-3 px-4">
                    {item.financial_center_name || '—'}
                  </td>
                  <td class="py-3 px-4">
                    {item.cost_center_name || '—'}
                  </td>
                  <td class="py-3 px-4">
                    {item.nomenclature_name || '—'}
                  </td>
                  <td class="py-3 px-4 font-medium">
                    <span class="{item.cost_sum > 0 ? 'text-red-600' : 'text-green-600'}">
                      {formatCurrency(item.cost_sum)}
                    </span>
                  </td>
                  <td class="py-3 px-4">
                    {#if item.comment_description}
                      <span class="text-sm text-slate-600" title={item.comment_description}>
                        {formatComment(item.comment_description)}
                      </span>
                    {:else}
                      <span class="text-slate-400">—</span>
                    {/if}
                  </td>
                </tr>
              {/each}
            </tbody>
          </table>
        </div>

        {#if facts.length >= 50}
          <div class="text-center py-4 border-t border-slate-200">
            <p class="text-sm text-slate-600">
              Показаны первые 50 записей. Используйте фильтры для уточнения поиска.
            </p>
          </div>
        {/if}
      {/if}
    </div>
  </Card>
</div>
